# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/adsb_receiver_fpga/receiver_adsb_fpga.srcs/sources_1/ip/my_module1_0_10/my_module1_0.xci
# IP: The module: 'my_module1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/adsb_receiver_fpga/receiver_adsb_fpga.srcs/sources_1/ip/my_module1_0_10/constraints/my_module1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_module1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/adsb_receiver_fpga/receiver_adsb_fpga.srcs/sources_1/ip/my_module1_0_10/my_module1_0.xci
# IP: The module: 'my_module1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/adsb_receiver_fpga/receiver_adsb_fpga.srcs/sources_1/ip/my_module1_0_10/constraints/my_module1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_module1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
