-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Seuil_calc1_do_gen is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    e_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    e_empty_n : IN STD_LOGIC;
    e_read : OUT STD_LOGIC;
    detect_din : OUT STD_LOGIC;
    detect_full_n : IN STD_LOGIC;
    detect_write : OUT STD_LOGIC );
end;


architecture behav of Seuil_calc1_do_gen is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_1F : STD_LOGIC_VECTOR (16 downto 0) := "00000000000011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv27_1B : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000011011";

    signal e_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal detect_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal val_V_reg_1395 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ps_V_fu_394_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ps_V_reg_1401 : STD_LOGIC_VECTOR (10 downto 0);
    signal ps_V_reg_1401_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal ps_V_reg_1401_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1069_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_reg_1406 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal grp_fu_1077_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_1_reg_1411 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1085_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_3_reg_1416 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1093_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_4_reg_1421 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1101_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_7_reg_1426 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1109_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_8_reg_1431 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1117_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_10_reg_1436 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1125_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_11_reg_1441 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1133_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_15_reg_1446 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1141_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_16_reg_1451 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1149_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_18_reg_1456 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1157_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_19_reg_1461 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1165_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_22_reg_1466 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1173_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_23_reg_1471 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1181_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_25_reg_1476 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1189_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_26_reg_1481 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln700_6_fu_873_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_6_reg_1486 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_13_fu_911_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_13_reg_1491 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_29_fu_1001_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_29_reg_1496 : STD_LOGIC_VECTOR (19 downto 0);
    signal res_2_V_1_fu_1040_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal res_2_V_1_reg_1501 : STD_LOGIC_VECTOR (16 downto 0);
    signal ret_V_fu_1197_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal ret_V_reg_1506 : STD_LOGIC_VECTOR (21 downto 0);
    signal mul_ln895_fu_1203_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal mul_ln895_reg_1511 : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal buffer_V_1_01066_fu_72 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_1_V_fu_76 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_2_V_fu_80 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_3_V_fu_84 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_4_V_fu_88 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_5_V_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_6_V_fu_96 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_7_V_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_8_V_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_9_V_fu_108 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_10_V_fu_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_11_V_fu_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_12_V_fu_120 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_13_V_fu_124 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_14_V_fu_128 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_15_V_fu_132 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_16_V_fu_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_17_V_fu_140 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_18_V_fu_144 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_19_V_fu_148 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_20_V_fu_152 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_21_V_fu_156 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_22_V_fu_160 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_23_V_fu_164 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_24_V_fu_168 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_25_V_fu_172 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_26_V_fu_176 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_27_V_fu_180 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_28_V_fu_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_29_V_fu_188 : STD_LOGIC_VECTOR (7 downto 0);
    signal buffer_30_V_fu_192 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln215_fu_302_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_1_fu_306_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln215_fu_334_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_3_fu_314_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_2_fu_310_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln215_1_fu_344_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_40_fu_340_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln215_41_fu_350_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln215_2_fu_354_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln215_5_fu_322_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_4_fu_318_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln215_3_fu_364_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_7_fu_330_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_6_fu_326_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln215_4_fu_374_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln215_43_fu_370_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln215_44_fu_380_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln215_5_fu_384_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln215_42_fu_360_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln215_45_fu_390_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1352_fu_404_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_8_fu_400_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_fu_404_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_fu_404_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_3_fu_426_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_11_fu_422_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_3_fu_426_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_3_fu_426_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_5_fu_444_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_13_fu_440_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_5_fu_444_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_5_fu_444_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_7_fu_462_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_15_fu_458_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_7_fu_462_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_7_fu_462_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_9_fu_480_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_17_fu_476_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_9_fu_480_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_9_fu_480_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_11_fu_498_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_19_fu_494_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_11_fu_498_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_11_fu_498_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_13_fu_516_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_21_fu_512_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_13_fu_516_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_13_fu_516_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_15_fu_534_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_23_fu_530_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_15_fu_534_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_15_fu_534_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_17_fu_552_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_25_fu_548_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_17_fu_552_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_17_fu_552_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_19_fu_570_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_27_fu_566_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_19_fu_570_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_19_fu_570_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_21_fu_588_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_29_fu_584_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_21_fu_588_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_21_fu_588_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_23_fu_606_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_31_fu_602_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_23_fu_606_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_23_fu_606_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_25_fu_624_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_33_fu_620_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_25_fu_624_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_25_fu_624_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_27_fu_642_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_35_fu_638_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_27_fu_642_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_27_fu_642_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_29_fu_660_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_37_fu_656_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_29_fu_660_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_29_fu_660_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_31_fu_677_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_39_fu_674_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1352_31_fu_677_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1352_31_fu_677_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln700_1_fu_841_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_2_fu_844_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_2_fu_847_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_4_fu_857_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_5_fu_860_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_5_fu_863_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_3_fu_853_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_6_fu_869_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_8_fu_879_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_9_fu_882_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_9_fu_885_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_11_fu_895_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_12_fu_898_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_12_fu_901_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_10_fu_891_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_13_fu_907_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_15_fu_917_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_16_fu_920_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_17_fu_923_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_18_fu_933_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_19_fu_936_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_20_fu_939_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_17_fu_929_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_20_fu_945_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_21_fu_949_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_22_fu_959_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_23_fu_962_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_24_fu_965_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_25_fu_975_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_26_fu_978_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln700_27_fu_981_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln700_24_fu_971_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_27_fu_987_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln700_28_fu_991_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln700_21_fu_955_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln700_28_fu_997_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln700_7_fu_1007_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln700_14_fu_1010_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_14_fu_1013_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln700_30_fu_1019_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_fu_1024_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln879_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln895_1_fu_1054_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal icmp_ln895_fu_1057_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_1069_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_9_fu_414_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1069_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1069_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1077_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_10_fu_418_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1077_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1077_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1085_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_12_fu_436_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1085_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1085_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1093_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_14_fu_454_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1093_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1093_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1101_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_16_fu_472_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1101_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1101_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1109_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_18_fu_490_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1109_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1109_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1117_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_20_fu_508_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1117_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1117_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1125_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_22_fu_526_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1125_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1125_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1133_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_24_fu_544_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1133_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1133_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1141_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_26_fu_562_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1141_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1141_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1149_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_28_fu_580_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1149_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1149_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1157_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_30_fu_598_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1157_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1157_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1165_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_32_fu_616_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1165_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1165_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1173_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_34_fu_634_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1173_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1173_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1181_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_36_fu_652_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1181_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1181_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1189_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln215_38_fu_670_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1189_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1189_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ret_V_fu_1197_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal lhs_V_fu_1048_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal ret_V_fu_1197_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln895_fu_1203_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln895_fu_1203_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_1069_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1077_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1085_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1093_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1101_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1109_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1117_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1125_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1133_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1141_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1149_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1157_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1165_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1173_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1181_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1189_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln895_fu_1203_p00 : STD_LOGIC_VECTOR (26 downto 0);

    component Seuil_calc1_mac_mdEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component Seuil_calc1_mul_meOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component Seuil_calc1_mul_mfYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (26 downto 0) );
    end component;



begin
    Seuil_calc1_mac_mdEe_U22 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1069_p0,
        din1 => grp_fu_1069_p1,
        din2 => grp_fu_1069_p2,
        dout => grp_fu_1069_p3);

    Seuil_calc1_mac_mdEe_U23 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1077_p0,
        din1 => grp_fu_1077_p1,
        din2 => grp_fu_1077_p2,
        dout => grp_fu_1077_p3);

    Seuil_calc1_mac_mdEe_U24 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1085_p0,
        din1 => grp_fu_1085_p1,
        din2 => grp_fu_1085_p2,
        dout => grp_fu_1085_p3);

    Seuil_calc1_mac_mdEe_U25 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1093_p0,
        din1 => grp_fu_1093_p1,
        din2 => grp_fu_1093_p2,
        dout => grp_fu_1093_p3);

    Seuil_calc1_mac_mdEe_U26 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1101_p0,
        din1 => grp_fu_1101_p1,
        din2 => grp_fu_1101_p2,
        dout => grp_fu_1101_p3);

    Seuil_calc1_mac_mdEe_U27 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1109_p0,
        din1 => grp_fu_1109_p1,
        din2 => grp_fu_1109_p2,
        dout => grp_fu_1109_p3);

    Seuil_calc1_mac_mdEe_U28 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1117_p0,
        din1 => grp_fu_1117_p1,
        din2 => grp_fu_1117_p2,
        dout => grp_fu_1117_p3);

    Seuil_calc1_mac_mdEe_U29 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1125_p0,
        din1 => grp_fu_1125_p1,
        din2 => grp_fu_1125_p2,
        dout => grp_fu_1125_p3);

    Seuil_calc1_mac_mdEe_U30 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1133_p0,
        din1 => grp_fu_1133_p1,
        din2 => grp_fu_1133_p2,
        dout => grp_fu_1133_p3);

    Seuil_calc1_mac_mdEe_U31 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1141_p0,
        din1 => grp_fu_1141_p1,
        din2 => grp_fu_1141_p2,
        dout => grp_fu_1141_p3);

    Seuil_calc1_mac_mdEe_U32 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1149_p0,
        din1 => grp_fu_1149_p1,
        din2 => grp_fu_1149_p2,
        dout => grp_fu_1149_p3);

    Seuil_calc1_mac_mdEe_U33 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1157_p0,
        din1 => grp_fu_1157_p1,
        din2 => grp_fu_1157_p2,
        dout => grp_fu_1157_p3);

    Seuil_calc1_mac_mdEe_U34 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1165_p0,
        din1 => grp_fu_1165_p1,
        din2 => grp_fu_1165_p2,
        dout => grp_fu_1165_p3);

    Seuil_calc1_mac_mdEe_U35 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1173_p0,
        din1 => grp_fu_1173_p1,
        din2 => grp_fu_1173_p2,
        dout => grp_fu_1173_p3);

    Seuil_calc1_mac_mdEe_U36 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1181_p0,
        din1 => grp_fu_1181_p1,
        din2 => grp_fu_1181_p2,
        dout => grp_fu_1181_p3);

    Seuil_calc1_mac_mdEe_U37 : component Seuil_calc1_mac_mdEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        din0 => grp_fu_1189_p0,
        din1 => grp_fu_1189_p1,
        din2 => grp_fu_1189_p2,
        dout => grp_fu_1189_p3);

    Seuil_calc1_mul_meOg_U38 : component Seuil_calc1_mul_meOg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 11,
        dout_WIDTH => 22)
    port map (
        din0 => ret_V_fu_1197_p0,
        din1 => ret_V_fu_1197_p1,
        dout => ret_V_fu_1197_p2);

    Seuil_calc1_mul_mfYi_U39 : component Seuil_calc1_mul_mfYi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 17,
        din1_WIDTH => 6,
        dout_WIDTH => 27)
    port map (
        din0 => mul_ln895_fu_1203_p0,
        din1 => mul_ln895_fu_1203_p1,
        dout => mul_ln895_fu_1203_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln700_10_reg_1436 <= grp_fu_1117_p3;
                add_ln700_11_reg_1441 <= grp_fu_1125_p3;
                add_ln700_15_reg_1446 <= grp_fu_1133_p3;
                add_ln700_16_reg_1451 <= grp_fu_1141_p3;
                add_ln700_18_reg_1456 <= grp_fu_1149_p3;
                add_ln700_19_reg_1461 <= grp_fu_1157_p3;
                add_ln700_1_reg_1411 <= grp_fu_1077_p3;
                add_ln700_22_reg_1466 <= grp_fu_1165_p3;
                add_ln700_23_reg_1471 <= grp_fu_1173_p3;
                add_ln700_25_reg_1476 <= grp_fu_1181_p3;
                add_ln700_26_reg_1481 <= grp_fu_1189_p3;
                add_ln700_3_reg_1416 <= grp_fu_1085_p3;
                add_ln700_4_reg_1421 <= grp_fu_1093_p3;
                add_ln700_7_reg_1426 <= grp_fu_1101_p3;
                add_ln700_8_reg_1431 <= grp_fu_1109_p3;
                add_ln700_reg_1406 <= grp_fu_1069_p3;
                buffer_10_V_fu_112 <= buffer_11_V_fu_116;
                buffer_11_V_fu_116 <= buffer_12_V_fu_120;
                buffer_12_V_fu_120 <= buffer_13_V_fu_124;
                buffer_13_V_fu_124 <= buffer_14_V_fu_128;
                buffer_14_V_fu_128 <= buffer_15_V_fu_132;
                buffer_15_V_fu_132 <= buffer_16_V_fu_136;
                buffer_16_V_fu_136 <= buffer_17_V_fu_140;
                buffer_17_V_fu_140 <= buffer_18_V_fu_144;
                buffer_18_V_fu_144 <= buffer_19_V_fu_148;
                buffer_19_V_fu_148 <= buffer_20_V_fu_152;
                buffer_1_V_fu_76 <= buffer_2_V_fu_80;
                buffer_20_V_fu_152 <= buffer_21_V_fu_156;
                buffer_21_V_fu_156 <= buffer_22_V_fu_160;
                buffer_22_V_fu_160 <= buffer_23_V_fu_164;
                buffer_23_V_fu_164 <= buffer_24_V_fu_168;
                buffer_24_V_fu_168 <= buffer_25_V_fu_172;
                buffer_25_V_fu_172 <= buffer_26_V_fu_176;
                buffer_26_V_fu_176 <= buffer_27_V_fu_180;
                buffer_27_V_fu_180 <= buffer_28_V_fu_184;
                buffer_28_V_fu_184 <= buffer_29_V_fu_188;
                buffer_29_V_fu_188 <= buffer_30_V_fu_192;
                buffer_2_V_fu_80 <= buffer_3_V_fu_84;
                buffer_30_V_fu_192 <= val_V_reg_1395;
                buffer_3_V_fu_84 <= buffer_4_V_fu_88;
                buffer_4_V_fu_88 <= buffer_5_V_fu_92;
                buffer_5_V_fu_92 <= buffer_6_V_fu_96;
                buffer_6_V_fu_96 <= buffer_7_V_fu_100;
                buffer_7_V_fu_100 <= buffer_8_V_fu_104;
                buffer_8_V_fu_104 <= buffer_9_V_fu_108;
                buffer_9_V_fu_108 <= buffer_10_V_fu_112;
                buffer_V_1_01066_fu_72 <= buffer_1_V_fu_76;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln700_13_reg_1491 <= add_ln700_13_fu_911_p2;
                add_ln700_29_reg_1496 <= add_ln700_29_fu_1001_p2;
                add_ln700_6_reg_1486 <= add_ln700_6_fu_873_p2;
                mul_ln895_reg_1511 <= mul_ln895_fu_1203_p2;
                ps_V_reg_1401_pp0_iter2_reg <= ps_V_reg_1401;
                ps_V_reg_1401_pp0_iter3_reg <= ps_V_reg_1401_pp0_iter2_reg;
                res_2_V_1_reg_1501 <= res_2_V_1_fu_1040_p3;
                ret_V_reg_1506 <= ret_V_fu_1197_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ps_V_reg_1401 <= ps_V_fu_394_p2;
                val_V_reg_1395 <= e_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln215_1_fu_344_p2 <= std_logic_vector(unsigned(zext_ln215_3_fu_314_p1) + unsigned(zext_ln215_2_fu_310_p1));
    add_ln215_2_fu_354_p2 <= std_logic_vector(unsigned(zext_ln215_40_fu_340_p1) + unsigned(zext_ln215_41_fu_350_p1));
    add_ln215_3_fu_364_p2 <= std_logic_vector(unsigned(zext_ln215_5_fu_322_p1) + unsigned(zext_ln215_4_fu_318_p1));
    add_ln215_4_fu_374_p2 <= std_logic_vector(unsigned(zext_ln215_7_fu_330_p1) + unsigned(zext_ln215_6_fu_326_p1));
    add_ln215_5_fu_384_p2 <= std_logic_vector(unsigned(zext_ln215_43_fu_370_p1) + unsigned(zext_ln215_44_fu_380_p1));
    add_ln215_fu_334_p2 <= std_logic_vector(unsigned(zext_ln215_fu_302_p1) + unsigned(zext_ln215_1_fu_306_p1));
    add_ln700_12_fu_901_p2 <= std_logic_vector(unsigned(zext_ln700_11_fu_895_p1) + unsigned(zext_ln700_12_fu_898_p1));
    add_ln700_13_fu_911_p2 <= std_logic_vector(unsigned(zext_ln700_10_fu_891_p1) + unsigned(zext_ln700_13_fu_907_p1));
    add_ln700_14_fu_1013_p2 <= std_logic_vector(unsigned(zext_ln700_7_fu_1007_p1) + unsigned(zext_ln700_14_fu_1010_p1));
    add_ln700_17_fu_923_p2 <= std_logic_vector(unsigned(zext_ln700_15_fu_917_p1) + unsigned(zext_ln700_16_fu_920_p1));
    add_ln700_20_fu_939_p2 <= std_logic_vector(unsigned(zext_ln700_18_fu_933_p1) + unsigned(zext_ln700_19_fu_936_p1));
    add_ln700_21_fu_949_p2 <= std_logic_vector(unsigned(zext_ln700_17_fu_929_p1) + unsigned(zext_ln700_20_fu_945_p1));
    add_ln700_24_fu_965_p2 <= std_logic_vector(unsigned(zext_ln700_22_fu_959_p1) + unsigned(zext_ln700_23_fu_962_p1));
    add_ln700_27_fu_981_p2 <= std_logic_vector(unsigned(zext_ln700_25_fu_975_p1) + unsigned(zext_ln700_26_fu_978_p1));
    add_ln700_28_fu_991_p2 <= std_logic_vector(unsigned(zext_ln700_24_fu_971_p1) + unsigned(zext_ln700_27_fu_987_p1));
    add_ln700_29_fu_1001_p2 <= std_logic_vector(unsigned(zext_ln700_21_fu_955_p1) + unsigned(zext_ln700_28_fu_997_p1));
    add_ln700_2_fu_847_p2 <= std_logic_vector(unsigned(zext_ln700_1_fu_841_p1) + unsigned(zext_ln700_2_fu_844_p1));
    add_ln700_30_fu_1019_p2 <= std_logic_vector(unsigned(add_ln700_29_reg_1496) + unsigned(add_ln700_14_fu_1013_p2));
    add_ln700_5_fu_863_p2 <= std_logic_vector(unsigned(zext_ln700_4_fu_857_p1) + unsigned(zext_ln700_5_fu_860_p1));
    add_ln700_6_fu_873_p2 <= std_logic_vector(unsigned(zext_ln700_3_fu_853_p1) + unsigned(zext_ln700_6_fu_869_p1));
    add_ln700_9_fu_885_p2 <= std_logic_vector(unsigned(zext_ln700_8_fu_879_p1) + unsigned(zext_ln700_9_fu_882_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(e_empty_n, detect_full_n, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5)
    begin
                ap_block_pp0_stage0_01001 <= (((detect_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((e_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(e_empty_n, detect_full_n, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5)
    begin
                ap_block_pp0_stage0_11001 <= (((detect_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((e_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(e_empty_n, detect_full_n, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5)
    begin
                ap_block_pp0_stage0_subdone <= (((detect_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((e_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(e_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter0 <= (e_empty_n = ap_const_logic_0);
    end process;

        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp0_stage0_iter5_assign_proc : process(detect_full_n)
    begin
                ap_block_state7_pp0_stage0_iter5 <= (detect_full_n = ap_const_logic_0);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    detect_blk_n_assign_proc : process(detect_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            detect_blk_n <= detect_full_n;
        else 
            detect_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    detect_din <= (icmp_ln895_fu_1057_p2(0) xor ap_const_logic_1);

    detect_write_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            detect_write <= ap_const_logic_1;
        else 
            detect_write <= ap_const_logic_0;
        end if; 
    end process;


    e_blk_n_assign_proc : process(e_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            e_blk_n <= e_empty_n;
        else 
            e_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    e_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            e_read <= ap_const_logic_1;
        else 
            e_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_1069_p0 <= zext_ln215_9_fu_414_p1(8 - 1 downto 0);
    grp_fu_1069_p1 <= zext_ln215_9_fu_414_p1(8 - 1 downto 0);
    grp_fu_1069_p2 <= grp_fu_1069_p20(16 - 1 downto 0);
    grp_fu_1069_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_fu_404_p2),17));
    grp_fu_1077_p0 <= zext_ln215_10_fu_418_p1(8 - 1 downto 0);
    grp_fu_1077_p1 <= zext_ln215_10_fu_418_p1(8 - 1 downto 0);
    grp_fu_1077_p2 <= grp_fu_1077_p20(16 - 1 downto 0);
    grp_fu_1077_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_3_fu_426_p2),17));
    grp_fu_1085_p0 <= zext_ln215_12_fu_436_p1(8 - 1 downto 0);
    grp_fu_1085_p1 <= zext_ln215_12_fu_436_p1(8 - 1 downto 0);
    grp_fu_1085_p2 <= grp_fu_1085_p20(16 - 1 downto 0);
    grp_fu_1085_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_5_fu_444_p2),17));
    grp_fu_1093_p0 <= zext_ln215_14_fu_454_p1(8 - 1 downto 0);
    grp_fu_1093_p1 <= zext_ln215_14_fu_454_p1(8 - 1 downto 0);
    grp_fu_1093_p2 <= grp_fu_1093_p20(16 - 1 downto 0);
    grp_fu_1093_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_7_fu_462_p2),17));
    grp_fu_1101_p0 <= zext_ln215_16_fu_472_p1(8 - 1 downto 0);
    grp_fu_1101_p1 <= zext_ln215_16_fu_472_p1(8 - 1 downto 0);
    grp_fu_1101_p2 <= grp_fu_1101_p20(16 - 1 downto 0);
    grp_fu_1101_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_9_fu_480_p2),17));
    grp_fu_1109_p0 <= zext_ln215_18_fu_490_p1(8 - 1 downto 0);
    grp_fu_1109_p1 <= zext_ln215_18_fu_490_p1(8 - 1 downto 0);
    grp_fu_1109_p2 <= grp_fu_1109_p20(16 - 1 downto 0);
    grp_fu_1109_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_11_fu_498_p2),17));
    grp_fu_1117_p0 <= zext_ln215_20_fu_508_p1(8 - 1 downto 0);
    grp_fu_1117_p1 <= zext_ln215_20_fu_508_p1(8 - 1 downto 0);
    grp_fu_1117_p2 <= grp_fu_1117_p20(16 - 1 downto 0);
    grp_fu_1117_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_13_fu_516_p2),17));
    grp_fu_1125_p0 <= zext_ln215_22_fu_526_p1(8 - 1 downto 0);
    grp_fu_1125_p1 <= zext_ln215_22_fu_526_p1(8 - 1 downto 0);
    grp_fu_1125_p2 <= grp_fu_1125_p20(16 - 1 downto 0);
    grp_fu_1125_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_15_fu_534_p2),17));
    grp_fu_1133_p0 <= zext_ln215_24_fu_544_p1(8 - 1 downto 0);
    grp_fu_1133_p1 <= zext_ln215_24_fu_544_p1(8 - 1 downto 0);
    grp_fu_1133_p2 <= grp_fu_1133_p20(16 - 1 downto 0);
    grp_fu_1133_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_17_fu_552_p2),17));
    grp_fu_1141_p0 <= zext_ln215_26_fu_562_p1(8 - 1 downto 0);
    grp_fu_1141_p1 <= zext_ln215_26_fu_562_p1(8 - 1 downto 0);
    grp_fu_1141_p2 <= grp_fu_1141_p20(16 - 1 downto 0);
    grp_fu_1141_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_19_fu_570_p2),17));
    grp_fu_1149_p0 <= zext_ln215_28_fu_580_p1(8 - 1 downto 0);
    grp_fu_1149_p1 <= zext_ln215_28_fu_580_p1(8 - 1 downto 0);
    grp_fu_1149_p2 <= grp_fu_1149_p20(16 - 1 downto 0);
    grp_fu_1149_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_21_fu_588_p2),17));
    grp_fu_1157_p0 <= zext_ln215_30_fu_598_p1(8 - 1 downto 0);
    grp_fu_1157_p1 <= zext_ln215_30_fu_598_p1(8 - 1 downto 0);
    grp_fu_1157_p2 <= grp_fu_1157_p20(16 - 1 downto 0);
    grp_fu_1157_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_23_fu_606_p2),17));
    grp_fu_1165_p0 <= zext_ln215_32_fu_616_p1(8 - 1 downto 0);
    grp_fu_1165_p1 <= zext_ln215_32_fu_616_p1(8 - 1 downto 0);
    grp_fu_1165_p2 <= grp_fu_1165_p20(16 - 1 downto 0);
    grp_fu_1165_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_25_fu_624_p2),17));
    grp_fu_1173_p0 <= zext_ln215_34_fu_634_p1(8 - 1 downto 0);
    grp_fu_1173_p1 <= zext_ln215_34_fu_634_p1(8 - 1 downto 0);
    grp_fu_1173_p2 <= grp_fu_1173_p20(16 - 1 downto 0);
    grp_fu_1173_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_27_fu_642_p2),17));
    grp_fu_1181_p0 <= zext_ln215_36_fu_652_p1(8 - 1 downto 0);
    grp_fu_1181_p1 <= zext_ln215_36_fu_652_p1(8 - 1 downto 0);
    grp_fu_1181_p2 <= grp_fu_1181_p20(16 - 1 downto 0);
    grp_fu_1181_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_29_fu_660_p2),17));
    grp_fu_1189_p0 <= zext_ln215_38_fu_670_p1(8 - 1 downto 0);
    grp_fu_1189_p1 <= zext_ln215_38_fu_670_p1(8 - 1 downto 0);
    grp_fu_1189_p2 <= grp_fu_1189_p20(16 - 1 downto 0);
    grp_fu_1189_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_31_fu_677_p2),17));
    icmp_ln879_fu_1034_p2 <= "1" when (r_V_fu_1024_p4 = ap_const_lv17_0) else "0";
    icmp_ln895_fu_1057_p2 <= "1" when (unsigned(zext_ln895_1_fu_1054_p1) < unsigned(mul_ln895_reg_1511)) else "0";
    lhs_V_fu_1048_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ps_V_reg_1401_pp0_iter3_reg),22));
    mul_ln1352_11_fu_498_p0 <= zext_ln215_19_fu_494_p1(8 - 1 downto 0);
    mul_ln1352_11_fu_498_p1 <= zext_ln215_19_fu_494_p1(8 - 1 downto 0);
    mul_ln1352_11_fu_498_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_11_fu_498_p0) * unsigned(mul_ln1352_11_fu_498_p1), 16));
    mul_ln1352_13_fu_516_p0 <= zext_ln215_21_fu_512_p1(8 - 1 downto 0);
    mul_ln1352_13_fu_516_p1 <= zext_ln215_21_fu_512_p1(8 - 1 downto 0);
    mul_ln1352_13_fu_516_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_13_fu_516_p0) * unsigned(mul_ln1352_13_fu_516_p1), 16));
    mul_ln1352_15_fu_534_p0 <= zext_ln215_23_fu_530_p1(8 - 1 downto 0);
    mul_ln1352_15_fu_534_p1 <= zext_ln215_23_fu_530_p1(8 - 1 downto 0);
    mul_ln1352_15_fu_534_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_15_fu_534_p0) * unsigned(mul_ln1352_15_fu_534_p1), 16));
    mul_ln1352_17_fu_552_p0 <= zext_ln215_25_fu_548_p1(8 - 1 downto 0);
    mul_ln1352_17_fu_552_p1 <= zext_ln215_25_fu_548_p1(8 - 1 downto 0);
    mul_ln1352_17_fu_552_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_17_fu_552_p0) * unsigned(mul_ln1352_17_fu_552_p1), 16));
    mul_ln1352_19_fu_570_p0 <= zext_ln215_27_fu_566_p1(8 - 1 downto 0);
    mul_ln1352_19_fu_570_p1 <= zext_ln215_27_fu_566_p1(8 - 1 downto 0);
    mul_ln1352_19_fu_570_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_19_fu_570_p0) * unsigned(mul_ln1352_19_fu_570_p1), 16));
    mul_ln1352_21_fu_588_p0 <= zext_ln215_29_fu_584_p1(8 - 1 downto 0);
    mul_ln1352_21_fu_588_p1 <= zext_ln215_29_fu_584_p1(8 - 1 downto 0);
    mul_ln1352_21_fu_588_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_21_fu_588_p0) * unsigned(mul_ln1352_21_fu_588_p1), 16));
    mul_ln1352_23_fu_606_p0 <= zext_ln215_31_fu_602_p1(8 - 1 downto 0);
    mul_ln1352_23_fu_606_p1 <= zext_ln215_31_fu_602_p1(8 - 1 downto 0);
    mul_ln1352_23_fu_606_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_23_fu_606_p0) * unsigned(mul_ln1352_23_fu_606_p1), 16));
    mul_ln1352_25_fu_624_p0 <= zext_ln215_33_fu_620_p1(8 - 1 downto 0);
    mul_ln1352_25_fu_624_p1 <= zext_ln215_33_fu_620_p1(8 - 1 downto 0);
    mul_ln1352_25_fu_624_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_25_fu_624_p0) * unsigned(mul_ln1352_25_fu_624_p1), 16));
    mul_ln1352_27_fu_642_p0 <= zext_ln215_35_fu_638_p1(8 - 1 downto 0);
    mul_ln1352_27_fu_642_p1 <= zext_ln215_35_fu_638_p1(8 - 1 downto 0);
    mul_ln1352_27_fu_642_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_27_fu_642_p0) * unsigned(mul_ln1352_27_fu_642_p1), 16));
    mul_ln1352_29_fu_660_p0 <= zext_ln215_37_fu_656_p1(8 - 1 downto 0);
    mul_ln1352_29_fu_660_p1 <= zext_ln215_37_fu_656_p1(8 - 1 downto 0);
    mul_ln1352_29_fu_660_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_29_fu_660_p0) * unsigned(mul_ln1352_29_fu_660_p1), 16));
    mul_ln1352_31_fu_677_p0 <= zext_ln215_39_fu_674_p1(8 - 1 downto 0);
    mul_ln1352_31_fu_677_p1 <= zext_ln215_39_fu_674_p1(8 - 1 downto 0);
    mul_ln1352_31_fu_677_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_31_fu_677_p0) * unsigned(mul_ln1352_31_fu_677_p1), 16));
    mul_ln1352_3_fu_426_p0 <= zext_ln215_11_fu_422_p1(8 - 1 downto 0);
    mul_ln1352_3_fu_426_p1 <= zext_ln215_11_fu_422_p1(8 - 1 downto 0);
    mul_ln1352_3_fu_426_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_3_fu_426_p0) * unsigned(mul_ln1352_3_fu_426_p1), 16));
    mul_ln1352_5_fu_444_p0 <= zext_ln215_13_fu_440_p1(8 - 1 downto 0);
    mul_ln1352_5_fu_444_p1 <= zext_ln215_13_fu_440_p1(8 - 1 downto 0);
    mul_ln1352_5_fu_444_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_5_fu_444_p0) * unsigned(mul_ln1352_5_fu_444_p1), 16));
    mul_ln1352_7_fu_462_p0 <= zext_ln215_15_fu_458_p1(8 - 1 downto 0);
    mul_ln1352_7_fu_462_p1 <= zext_ln215_15_fu_458_p1(8 - 1 downto 0);
    mul_ln1352_7_fu_462_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_7_fu_462_p0) * unsigned(mul_ln1352_7_fu_462_p1), 16));
    mul_ln1352_9_fu_480_p0 <= zext_ln215_17_fu_476_p1(8 - 1 downto 0);
    mul_ln1352_9_fu_480_p1 <= zext_ln215_17_fu_476_p1(8 - 1 downto 0);
    mul_ln1352_9_fu_480_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_9_fu_480_p0) * unsigned(mul_ln1352_9_fu_480_p1), 16));
    mul_ln1352_fu_404_p0 <= zext_ln215_8_fu_400_p1(8 - 1 downto 0);
    mul_ln1352_fu_404_p1 <= zext_ln215_8_fu_400_p1(8 - 1 downto 0);
    mul_ln1352_fu_404_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln1352_fu_404_p0) * unsigned(mul_ln1352_fu_404_p1), 16));
    mul_ln895_fu_1203_p0 <= mul_ln895_fu_1203_p00(17 - 1 downto 0);
    mul_ln895_fu_1203_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(res_2_V_1_reg_1501),27));
    mul_ln895_fu_1203_p1 <= ap_const_lv27_1B(6 - 1 downto 0);
    ps_V_fu_394_p2 <= std_logic_vector(unsigned(zext_ln215_42_fu_360_p1) + unsigned(zext_ln215_45_fu_390_p1));
    r_V_fu_1024_p4 <= add_ln700_30_fu_1019_p2(18 downto 2);
    res_2_V_1_fu_1040_p3 <= 
        ap_const_lv17_1F when (icmp_ln879_fu_1034_p2(0) = '1') else 
        r_V_fu_1024_p4;
    ret_V_fu_1197_p0 <= lhs_V_fu_1048_p1(11 - 1 downto 0);
    ret_V_fu_1197_p1 <= lhs_V_fu_1048_p1(11 - 1 downto 0);
    zext_ln215_10_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_2_V_fu_80),16));
    zext_ln215_11_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_3_V_fu_84),16));
    zext_ln215_12_fu_436_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_4_V_fu_88),16));
    zext_ln215_13_fu_440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_5_V_fu_92),16));
    zext_ln215_14_fu_454_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_6_V_fu_96),16));
    zext_ln215_15_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_7_V_fu_100),16));
    zext_ln215_16_fu_472_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_8_V_fu_104),16));
    zext_ln215_17_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_9_V_fu_108),16));
    zext_ln215_18_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_10_V_fu_112),16));
    zext_ln215_19_fu_494_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_11_V_fu_116),16));
    zext_ln215_1_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_1_V_fu_76),9));
    zext_ln215_20_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_12_V_fu_120),16));
    zext_ln215_21_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_13_V_fu_124),16));
    zext_ln215_22_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_14_V_fu_128),16));
    zext_ln215_23_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_15_V_fu_132),16));
    zext_ln215_24_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_16_V_fu_136),16));
    zext_ln215_25_fu_548_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_17_V_fu_140),16));
    zext_ln215_26_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_18_V_fu_144),16));
    zext_ln215_27_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_19_V_fu_148),16));
    zext_ln215_28_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_20_V_fu_152),16));
    zext_ln215_29_fu_584_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_21_V_fu_156),16));
    zext_ln215_2_fu_310_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_4_V_fu_88),9));
    zext_ln215_30_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_22_V_fu_160),16));
    zext_ln215_31_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_23_V_fu_164),16));
    zext_ln215_32_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_24_V_fu_168),16));
    zext_ln215_33_fu_620_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_25_V_fu_172),16));
    zext_ln215_34_fu_634_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_26_V_fu_176),16));
    zext_ln215_35_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_27_V_fu_180),16));
    zext_ln215_36_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_28_V_fu_184),16));
    zext_ln215_37_fu_656_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_29_V_fu_188),16));
    zext_ln215_38_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_30_V_fu_192),16));
    zext_ln215_39_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_V_reg_1395),16));
    zext_ln215_3_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_5_V_fu_92),9));
    zext_ln215_40_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln215_fu_334_p2),10));
    zext_ln215_41_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln215_1_fu_344_p2),10));
    zext_ln215_42_fu_360_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln215_2_fu_354_p2),11));
    zext_ln215_43_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln215_3_fu_364_p2),10));
    zext_ln215_44_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln215_4_fu_374_p2),10));
    zext_ln215_45_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln215_5_fu_384_p2),11));
    zext_ln215_4_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_14_V_fu_128),9));
    zext_ln215_5_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_15_V_fu_132),9));
    zext_ln215_6_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_18_V_fu_144),9));
    zext_ln215_7_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_19_V_fu_148),9));
    zext_ln215_8_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_V_1_01066_fu_72),16));
    zext_ln215_9_fu_414_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_1_V_fu_76),16));
    zext_ln215_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(buffer_V_1_01066_fu_72),9));
    zext_ln700_10_fu_891_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_9_fu_885_p2),19));
    zext_ln700_11_fu_895_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_10_reg_1436),18));
    zext_ln700_12_fu_898_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_11_reg_1441),18));
    zext_ln700_13_fu_907_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_12_fu_901_p2),19));
    zext_ln700_14_fu_1010_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_13_reg_1491),20));
    zext_ln700_15_fu_917_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_15_reg_1446),18));
    zext_ln700_16_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_16_reg_1451),18));
    zext_ln700_17_fu_929_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_17_fu_923_p2),19));
    zext_ln700_18_fu_933_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_18_reg_1456),18));
    zext_ln700_19_fu_936_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_19_reg_1461),18));
    zext_ln700_1_fu_841_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_reg_1406),18));
    zext_ln700_20_fu_945_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_20_fu_939_p2),19));
    zext_ln700_21_fu_955_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_21_fu_949_p2),20));
    zext_ln700_22_fu_959_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_22_reg_1466),18));
    zext_ln700_23_fu_962_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_23_reg_1471),18));
    zext_ln700_24_fu_971_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_24_fu_965_p2),19));
    zext_ln700_25_fu_975_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_25_reg_1476),18));
    zext_ln700_26_fu_978_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_26_reg_1481),18));
    zext_ln700_27_fu_987_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_27_fu_981_p2),19));
    zext_ln700_28_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_28_fu_991_p2),20));
    zext_ln700_2_fu_844_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_1_reg_1411),18));
    zext_ln700_3_fu_853_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_2_fu_847_p2),19));
    zext_ln700_4_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_3_reg_1416),18));
    zext_ln700_5_fu_860_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_4_reg_1421),18));
    zext_ln700_6_fu_869_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_5_fu_863_p2),19));
    zext_ln700_7_fu_1007_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_6_reg_1486),20));
    zext_ln700_8_fu_879_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_7_reg_1426),18));
    zext_ln700_9_fu_882_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln700_8_reg_1431),18));
    zext_ln895_1_fu_1054_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_reg_1506),27));
end behav;
