# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/FPGA_RECEIVER_FLOAT/FPGA_RECEIVER_FLOAT.srcs/sources_1/ip/my_module_0/my_module_0.xci
# IP: The module: 'my_module_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/FPGA_RECEIVER_FLOAT/FPGA_RECEIVER_FLOAT.srcs/sources_1/ip/my_module_0/constraints/my_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_module_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/FPGA_RECEIVER_FLOAT/FPGA_RECEIVER_FLOAT.srcs/sources_1/ip/my_module_0/my_module_0.xci
# IP: The module: 'my_module_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oasa/Documents/ef/adsb-like-comm-toolbox/src/FPGA_RECEIVER_FLOAT/FPGA_RECEIVER_FLOAT.srcs/sources_1/ip/my_module_0/constraints/my_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_module_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
