// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Seuil_calc1_do_gen (
        ap_clk,
        ap_rst,
        e_dout,
        e_empty_n,
        e_read,
        detect_din,
        detect_full_n,
        detect_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input  [7:0] e_dout;
input   e_empty_n;
output   e_read;
output   detect_din;
input   detect_full_n;
output   detect_write;

reg e_read;
reg detect_write;

reg    e_blk_n;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    detect_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [7:0] val_V_reg_1395;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] ps_V_fu_394_p2;
reg   [10:0] ps_V_reg_1401;
reg   [10:0] ps_V_reg_1401_pp0_iter2_reg;
reg   [10:0] ps_V_reg_1401_pp0_iter3_reg;
wire   [16:0] grp_fu_1069_p3;
reg   [16:0] add_ln700_reg_1406;
reg    ap_enable_reg_pp0_iter1;
wire   [16:0] grp_fu_1077_p3;
reg   [16:0] add_ln700_1_reg_1411;
wire   [16:0] grp_fu_1085_p3;
reg   [16:0] add_ln700_3_reg_1416;
wire   [16:0] grp_fu_1093_p3;
reg   [16:0] add_ln700_4_reg_1421;
wire   [16:0] grp_fu_1101_p3;
reg   [16:0] add_ln700_7_reg_1426;
wire   [16:0] grp_fu_1109_p3;
reg   [16:0] add_ln700_8_reg_1431;
wire   [16:0] grp_fu_1117_p3;
reg   [16:0] add_ln700_10_reg_1436;
wire   [16:0] grp_fu_1125_p3;
reg   [16:0] add_ln700_11_reg_1441;
wire   [16:0] grp_fu_1133_p3;
reg   [16:0] add_ln700_15_reg_1446;
wire   [16:0] grp_fu_1141_p3;
reg   [16:0] add_ln700_16_reg_1451;
wire   [16:0] grp_fu_1149_p3;
reg   [16:0] add_ln700_18_reg_1456;
wire   [16:0] grp_fu_1157_p3;
reg   [16:0] add_ln700_19_reg_1461;
wire   [16:0] grp_fu_1165_p3;
reg   [16:0] add_ln700_22_reg_1466;
wire   [16:0] grp_fu_1173_p3;
reg   [16:0] add_ln700_23_reg_1471;
wire   [16:0] grp_fu_1181_p3;
reg   [16:0] add_ln700_25_reg_1476;
wire   [16:0] grp_fu_1189_p3;
reg   [16:0] add_ln700_26_reg_1481;
wire   [18:0] add_ln700_6_fu_873_p2;
reg   [18:0] add_ln700_6_reg_1486;
wire   [18:0] add_ln700_13_fu_911_p2;
reg   [18:0] add_ln700_13_reg_1491;
wire   [19:0] add_ln700_29_fu_1001_p2;
reg   [19:0] add_ln700_29_reg_1496;
wire   [16:0] res_2_V_1_fu_1040_p3;
reg   [16:0] res_2_V_1_reg_1501;
wire   [21:0] ret_V_fu_1197_p2;
reg   [21:0] ret_V_reg_1506;
wire   [26:0] mul_ln895_fu_1203_p2;
reg   [26:0] mul_ln895_reg_1511;
wire    ap_CS_fsm_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [7:0] buffer_V_1_01066_fu_72;
reg   [7:0] buffer_1_V_fu_76;
reg   [7:0] buffer_2_V_fu_80;
reg   [7:0] buffer_3_V_fu_84;
reg   [7:0] buffer_4_V_fu_88;
reg   [7:0] buffer_5_V_fu_92;
reg   [7:0] buffer_6_V_fu_96;
reg   [7:0] buffer_7_V_fu_100;
reg   [7:0] buffer_8_V_fu_104;
reg   [7:0] buffer_9_V_fu_108;
reg   [7:0] buffer_10_V_fu_112;
reg   [7:0] buffer_11_V_fu_116;
reg   [7:0] buffer_12_V_fu_120;
reg   [7:0] buffer_13_V_fu_124;
reg   [7:0] buffer_14_V_fu_128;
reg   [7:0] buffer_15_V_fu_132;
reg   [7:0] buffer_16_V_fu_136;
reg   [7:0] buffer_17_V_fu_140;
reg   [7:0] buffer_18_V_fu_144;
reg   [7:0] buffer_19_V_fu_148;
reg   [7:0] buffer_20_V_fu_152;
reg   [7:0] buffer_21_V_fu_156;
reg   [7:0] buffer_22_V_fu_160;
reg   [7:0] buffer_23_V_fu_164;
reg   [7:0] buffer_24_V_fu_168;
reg   [7:0] buffer_25_V_fu_172;
reg   [7:0] buffer_26_V_fu_176;
reg   [7:0] buffer_27_V_fu_180;
reg   [7:0] buffer_28_V_fu_184;
reg   [7:0] buffer_29_V_fu_188;
reg   [7:0] buffer_30_V_fu_192;
reg    ap_block_pp0_stage0_01001;
wire   [8:0] zext_ln215_fu_302_p1;
wire   [8:0] zext_ln215_1_fu_306_p1;
wire   [8:0] add_ln215_fu_334_p2;
wire   [8:0] zext_ln215_3_fu_314_p1;
wire   [8:0] zext_ln215_2_fu_310_p1;
wire   [8:0] add_ln215_1_fu_344_p2;
wire   [9:0] zext_ln215_40_fu_340_p1;
wire   [9:0] zext_ln215_41_fu_350_p1;
wire   [9:0] add_ln215_2_fu_354_p2;
wire   [8:0] zext_ln215_5_fu_322_p1;
wire   [8:0] zext_ln215_4_fu_318_p1;
wire   [8:0] add_ln215_3_fu_364_p2;
wire   [8:0] zext_ln215_7_fu_330_p1;
wire   [8:0] zext_ln215_6_fu_326_p1;
wire   [8:0] add_ln215_4_fu_374_p2;
wire   [9:0] zext_ln215_43_fu_370_p1;
wire   [9:0] zext_ln215_44_fu_380_p1;
wire   [9:0] add_ln215_5_fu_384_p2;
wire   [10:0] zext_ln215_42_fu_360_p1;
wire   [10:0] zext_ln215_45_fu_390_p1;
wire   [7:0] mul_ln1352_fu_404_p0;
wire   [15:0] zext_ln215_8_fu_400_p1;
wire   [7:0] mul_ln1352_fu_404_p1;
wire   [15:0] mul_ln1352_fu_404_p2;
wire   [7:0] mul_ln1352_3_fu_426_p0;
wire   [15:0] zext_ln215_11_fu_422_p1;
wire   [7:0] mul_ln1352_3_fu_426_p1;
wire   [15:0] mul_ln1352_3_fu_426_p2;
wire   [7:0] mul_ln1352_5_fu_444_p0;
wire   [15:0] zext_ln215_13_fu_440_p1;
wire   [7:0] mul_ln1352_5_fu_444_p1;
wire   [15:0] mul_ln1352_5_fu_444_p2;
wire   [7:0] mul_ln1352_7_fu_462_p0;
wire   [15:0] zext_ln215_15_fu_458_p1;
wire   [7:0] mul_ln1352_7_fu_462_p1;
wire   [15:0] mul_ln1352_7_fu_462_p2;
wire   [7:0] mul_ln1352_9_fu_480_p0;
wire   [15:0] zext_ln215_17_fu_476_p1;
wire   [7:0] mul_ln1352_9_fu_480_p1;
wire   [15:0] mul_ln1352_9_fu_480_p2;
wire   [7:0] mul_ln1352_11_fu_498_p0;
wire   [15:0] zext_ln215_19_fu_494_p1;
wire   [7:0] mul_ln1352_11_fu_498_p1;
wire   [15:0] mul_ln1352_11_fu_498_p2;
wire   [7:0] mul_ln1352_13_fu_516_p0;
wire   [15:0] zext_ln215_21_fu_512_p1;
wire   [7:0] mul_ln1352_13_fu_516_p1;
wire   [15:0] mul_ln1352_13_fu_516_p2;
wire   [7:0] mul_ln1352_15_fu_534_p0;
wire   [15:0] zext_ln215_23_fu_530_p1;
wire   [7:0] mul_ln1352_15_fu_534_p1;
wire   [15:0] mul_ln1352_15_fu_534_p2;
wire   [7:0] mul_ln1352_17_fu_552_p0;
wire   [15:0] zext_ln215_25_fu_548_p1;
wire   [7:0] mul_ln1352_17_fu_552_p1;
wire   [15:0] mul_ln1352_17_fu_552_p2;
wire   [7:0] mul_ln1352_19_fu_570_p0;
wire   [15:0] zext_ln215_27_fu_566_p1;
wire   [7:0] mul_ln1352_19_fu_570_p1;
wire   [15:0] mul_ln1352_19_fu_570_p2;
wire   [7:0] mul_ln1352_21_fu_588_p0;
wire   [15:0] zext_ln215_29_fu_584_p1;
wire   [7:0] mul_ln1352_21_fu_588_p1;
wire   [15:0] mul_ln1352_21_fu_588_p2;
wire   [7:0] mul_ln1352_23_fu_606_p0;
wire   [15:0] zext_ln215_31_fu_602_p1;
wire   [7:0] mul_ln1352_23_fu_606_p1;
wire   [15:0] mul_ln1352_23_fu_606_p2;
wire   [7:0] mul_ln1352_25_fu_624_p0;
wire   [15:0] zext_ln215_33_fu_620_p1;
wire   [7:0] mul_ln1352_25_fu_624_p1;
wire   [15:0] mul_ln1352_25_fu_624_p2;
wire   [7:0] mul_ln1352_27_fu_642_p0;
wire   [15:0] zext_ln215_35_fu_638_p1;
wire   [7:0] mul_ln1352_27_fu_642_p1;
wire   [15:0] mul_ln1352_27_fu_642_p2;
wire   [7:0] mul_ln1352_29_fu_660_p0;
wire   [15:0] zext_ln215_37_fu_656_p1;
wire   [7:0] mul_ln1352_29_fu_660_p1;
wire   [15:0] mul_ln1352_29_fu_660_p2;
wire   [7:0] mul_ln1352_31_fu_677_p0;
wire   [15:0] zext_ln215_39_fu_674_p1;
wire   [7:0] mul_ln1352_31_fu_677_p1;
wire   [15:0] mul_ln1352_31_fu_677_p2;
wire   [17:0] zext_ln700_1_fu_841_p1;
wire   [17:0] zext_ln700_2_fu_844_p1;
wire   [17:0] add_ln700_2_fu_847_p2;
wire   [17:0] zext_ln700_4_fu_857_p1;
wire   [17:0] zext_ln700_5_fu_860_p1;
wire   [17:0] add_ln700_5_fu_863_p2;
wire   [18:0] zext_ln700_3_fu_853_p1;
wire   [18:0] zext_ln700_6_fu_869_p1;
wire   [17:0] zext_ln700_8_fu_879_p1;
wire   [17:0] zext_ln700_9_fu_882_p1;
wire   [17:0] add_ln700_9_fu_885_p2;
wire   [17:0] zext_ln700_11_fu_895_p1;
wire   [17:0] zext_ln700_12_fu_898_p1;
wire   [17:0] add_ln700_12_fu_901_p2;
wire   [18:0] zext_ln700_10_fu_891_p1;
wire   [18:0] zext_ln700_13_fu_907_p1;
wire   [17:0] zext_ln700_15_fu_917_p1;
wire   [17:0] zext_ln700_16_fu_920_p1;
wire   [17:0] add_ln700_17_fu_923_p2;
wire   [17:0] zext_ln700_18_fu_933_p1;
wire   [17:0] zext_ln700_19_fu_936_p1;
wire   [17:0] add_ln700_20_fu_939_p2;
wire   [18:0] zext_ln700_17_fu_929_p1;
wire   [18:0] zext_ln700_20_fu_945_p1;
wire   [18:0] add_ln700_21_fu_949_p2;
wire   [17:0] zext_ln700_22_fu_959_p1;
wire   [17:0] zext_ln700_23_fu_962_p1;
wire   [17:0] add_ln700_24_fu_965_p2;
wire   [17:0] zext_ln700_25_fu_975_p1;
wire   [17:0] zext_ln700_26_fu_978_p1;
wire   [17:0] add_ln700_27_fu_981_p2;
wire   [18:0] zext_ln700_24_fu_971_p1;
wire   [18:0] zext_ln700_27_fu_987_p1;
wire   [18:0] add_ln700_28_fu_991_p2;
wire   [19:0] zext_ln700_21_fu_955_p1;
wire   [19:0] zext_ln700_28_fu_997_p1;
wire   [19:0] zext_ln700_7_fu_1007_p1;
wire   [19:0] zext_ln700_14_fu_1010_p1;
wire   [19:0] add_ln700_14_fu_1013_p2;
wire   [19:0] add_ln700_30_fu_1019_p2;
wire   [16:0] r_V_fu_1024_p4;
wire   [0:0] icmp_ln879_fu_1034_p2;
wire   [26:0] zext_ln895_1_fu_1054_p1;
wire   [0:0] icmp_ln895_fu_1057_p2;
wire   [7:0] grp_fu_1069_p0;
wire   [15:0] zext_ln215_9_fu_414_p1;
wire   [7:0] grp_fu_1069_p1;
wire   [15:0] grp_fu_1069_p2;
wire   [7:0] grp_fu_1077_p0;
wire   [15:0] zext_ln215_10_fu_418_p1;
wire   [7:0] grp_fu_1077_p1;
wire   [15:0] grp_fu_1077_p2;
wire   [7:0] grp_fu_1085_p0;
wire   [15:0] zext_ln215_12_fu_436_p1;
wire   [7:0] grp_fu_1085_p1;
wire   [15:0] grp_fu_1085_p2;
wire   [7:0] grp_fu_1093_p0;
wire   [15:0] zext_ln215_14_fu_454_p1;
wire   [7:0] grp_fu_1093_p1;
wire   [15:0] grp_fu_1093_p2;
wire   [7:0] grp_fu_1101_p0;
wire   [15:0] zext_ln215_16_fu_472_p1;
wire   [7:0] grp_fu_1101_p1;
wire   [15:0] grp_fu_1101_p2;
wire   [7:0] grp_fu_1109_p0;
wire   [15:0] zext_ln215_18_fu_490_p1;
wire   [7:0] grp_fu_1109_p1;
wire   [15:0] grp_fu_1109_p2;
wire   [7:0] grp_fu_1117_p0;
wire   [15:0] zext_ln215_20_fu_508_p1;
wire   [7:0] grp_fu_1117_p1;
wire   [15:0] grp_fu_1117_p2;
wire   [7:0] grp_fu_1125_p0;
wire   [15:0] zext_ln215_22_fu_526_p1;
wire   [7:0] grp_fu_1125_p1;
wire   [15:0] grp_fu_1125_p2;
wire   [7:0] grp_fu_1133_p0;
wire   [15:0] zext_ln215_24_fu_544_p1;
wire   [7:0] grp_fu_1133_p1;
wire   [15:0] grp_fu_1133_p2;
wire   [7:0] grp_fu_1141_p0;
wire   [15:0] zext_ln215_26_fu_562_p1;
wire   [7:0] grp_fu_1141_p1;
wire   [15:0] grp_fu_1141_p2;
wire   [7:0] grp_fu_1149_p0;
wire   [15:0] zext_ln215_28_fu_580_p1;
wire   [7:0] grp_fu_1149_p1;
wire   [15:0] grp_fu_1149_p2;
wire   [7:0] grp_fu_1157_p0;
wire   [15:0] zext_ln215_30_fu_598_p1;
wire   [7:0] grp_fu_1157_p1;
wire   [15:0] grp_fu_1157_p2;
wire   [7:0] grp_fu_1165_p0;
wire   [15:0] zext_ln215_32_fu_616_p1;
wire   [7:0] grp_fu_1165_p1;
wire   [15:0] grp_fu_1165_p2;
wire   [7:0] grp_fu_1173_p0;
wire   [15:0] zext_ln215_34_fu_634_p1;
wire   [7:0] grp_fu_1173_p1;
wire   [15:0] grp_fu_1173_p2;
wire   [7:0] grp_fu_1181_p0;
wire   [15:0] zext_ln215_36_fu_652_p1;
wire   [7:0] grp_fu_1181_p1;
wire   [15:0] grp_fu_1181_p2;
wire   [7:0] grp_fu_1189_p0;
wire   [15:0] zext_ln215_38_fu_670_p1;
wire   [7:0] grp_fu_1189_p1;
wire   [15:0] grp_fu_1189_p2;
wire   [10:0] ret_V_fu_1197_p0;
wire   [21:0] lhs_V_fu_1048_p1;
wire   [10:0] ret_V_fu_1197_p1;
wire   [16:0] mul_ln895_fu_1203_p0;
wire   [5:0] mul_ln895_fu_1203_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [16:0] grp_fu_1069_p20;
wire   [16:0] grp_fu_1077_p20;
wire   [16:0] grp_fu_1085_p20;
wire   [16:0] grp_fu_1093_p20;
wire   [16:0] grp_fu_1101_p20;
wire   [16:0] grp_fu_1109_p20;
wire   [16:0] grp_fu_1117_p20;
wire   [16:0] grp_fu_1125_p20;
wire   [16:0] grp_fu_1133_p20;
wire   [16:0] grp_fu_1141_p20;
wire   [16:0] grp_fu_1149_p20;
wire   [16:0] grp_fu_1157_p20;
wire   [16:0] grp_fu_1165_p20;
wire   [16:0] grp_fu_1173_p20;
wire   [16:0] grp_fu_1181_p20;
wire   [16:0] grp_fu_1189_p20;
wire   [26:0] mul_ln895_fu_1203_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U22(
    .din0(grp_fu_1069_p0),
    .din1(grp_fu_1069_p1),
    .din2(grp_fu_1069_p2),
    .dout(grp_fu_1069_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U23(
    .din0(grp_fu_1077_p0),
    .din1(grp_fu_1077_p1),
    .din2(grp_fu_1077_p2),
    .dout(grp_fu_1077_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U24(
    .din0(grp_fu_1085_p0),
    .din1(grp_fu_1085_p1),
    .din2(grp_fu_1085_p2),
    .dout(grp_fu_1085_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U25(
    .din0(grp_fu_1093_p0),
    .din1(grp_fu_1093_p1),
    .din2(grp_fu_1093_p2),
    .dout(grp_fu_1093_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U26(
    .din0(grp_fu_1101_p0),
    .din1(grp_fu_1101_p1),
    .din2(grp_fu_1101_p2),
    .dout(grp_fu_1101_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U27(
    .din0(grp_fu_1109_p0),
    .din1(grp_fu_1109_p1),
    .din2(grp_fu_1109_p2),
    .dout(grp_fu_1109_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U28(
    .din0(grp_fu_1117_p0),
    .din1(grp_fu_1117_p1),
    .din2(grp_fu_1117_p2),
    .dout(grp_fu_1117_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U29(
    .din0(grp_fu_1125_p0),
    .din1(grp_fu_1125_p1),
    .din2(grp_fu_1125_p2),
    .dout(grp_fu_1125_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U30(
    .din0(grp_fu_1133_p0),
    .din1(grp_fu_1133_p1),
    .din2(grp_fu_1133_p2),
    .dout(grp_fu_1133_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U31(
    .din0(grp_fu_1141_p0),
    .din1(grp_fu_1141_p1),
    .din2(grp_fu_1141_p2),
    .dout(grp_fu_1141_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U32(
    .din0(grp_fu_1149_p0),
    .din1(grp_fu_1149_p1),
    .din2(grp_fu_1149_p2),
    .dout(grp_fu_1149_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U33(
    .din0(grp_fu_1157_p0),
    .din1(grp_fu_1157_p1),
    .din2(grp_fu_1157_p2),
    .dout(grp_fu_1157_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U34(
    .din0(grp_fu_1165_p0),
    .din1(grp_fu_1165_p1),
    .din2(grp_fu_1165_p2),
    .dout(grp_fu_1165_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U35(
    .din0(grp_fu_1173_p0),
    .din1(grp_fu_1173_p1),
    .din2(grp_fu_1173_p2),
    .dout(grp_fu_1173_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U36(
    .din0(grp_fu_1181_p0),
    .din1(grp_fu_1181_p1),
    .din2(grp_fu_1181_p2),
    .dout(grp_fu_1181_p3)
);

Seuil_calc1_mac_mdEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
Seuil_calc1_mac_mdEe_U37(
    .din0(grp_fu_1189_p0),
    .din1(grp_fu_1189_p1),
    .din2(grp_fu_1189_p2),
    .dout(grp_fu_1189_p3)
);

Seuil_calc1_mul_meOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
Seuil_calc1_mul_meOg_U38(
    .din0(ret_V_fu_1197_p0),
    .din1(ret_V_fu_1197_p1),
    .dout(ret_V_fu_1197_p2)
);

Seuil_calc1_mul_mfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 27 ))
Seuil_calc1_mul_mfYi_U39(
    .din0(mul_ln895_fu_1203_p0),
    .din1(mul_ln895_fu_1203_p1),
    .dout(mul_ln895_fu_1203_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((1'b1 == ap_CS_fsm_state1)) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln700_10_reg_1436 <= grp_fu_1117_p3;
        add_ln700_11_reg_1441 <= grp_fu_1125_p3;
        add_ln700_15_reg_1446 <= grp_fu_1133_p3;
        add_ln700_16_reg_1451 <= grp_fu_1141_p3;
        add_ln700_18_reg_1456 <= grp_fu_1149_p3;
        add_ln700_19_reg_1461 <= grp_fu_1157_p3;
        add_ln700_1_reg_1411 <= grp_fu_1077_p3;
        add_ln700_22_reg_1466 <= grp_fu_1165_p3;
        add_ln700_23_reg_1471 <= grp_fu_1173_p3;
        add_ln700_25_reg_1476 <= grp_fu_1181_p3;
        add_ln700_26_reg_1481 <= grp_fu_1189_p3;
        add_ln700_3_reg_1416 <= grp_fu_1085_p3;
        add_ln700_4_reg_1421 <= grp_fu_1093_p3;
        add_ln700_7_reg_1426 <= grp_fu_1101_p3;
        add_ln700_8_reg_1431 <= grp_fu_1109_p3;
        add_ln700_reg_1406 <= grp_fu_1069_p3;
        buffer_10_V_fu_112 <= buffer_11_V_fu_116;
        buffer_11_V_fu_116 <= buffer_12_V_fu_120;
        buffer_12_V_fu_120 <= buffer_13_V_fu_124;
        buffer_13_V_fu_124 <= buffer_14_V_fu_128;
        buffer_14_V_fu_128 <= buffer_15_V_fu_132;
        buffer_15_V_fu_132 <= buffer_16_V_fu_136;
        buffer_16_V_fu_136 <= buffer_17_V_fu_140;
        buffer_17_V_fu_140 <= buffer_18_V_fu_144;
        buffer_18_V_fu_144 <= buffer_19_V_fu_148;
        buffer_19_V_fu_148 <= buffer_20_V_fu_152;
        buffer_1_V_fu_76 <= buffer_2_V_fu_80;
        buffer_20_V_fu_152 <= buffer_21_V_fu_156;
        buffer_21_V_fu_156 <= buffer_22_V_fu_160;
        buffer_22_V_fu_160 <= buffer_23_V_fu_164;
        buffer_23_V_fu_164 <= buffer_24_V_fu_168;
        buffer_24_V_fu_168 <= buffer_25_V_fu_172;
        buffer_25_V_fu_172 <= buffer_26_V_fu_176;
        buffer_26_V_fu_176 <= buffer_27_V_fu_180;
        buffer_27_V_fu_180 <= buffer_28_V_fu_184;
        buffer_28_V_fu_184 <= buffer_29_V_fu_188;
        buffer_29_V_fu_188 <= buffer_30_V_fu_192;
        buffer_2_V_fu_80 <= buffer_3_V_fu_84;
        buffer_30_V_fu_192 <= val_V_reg_1395;
        buffer_3_V_fu_84 <= buffer_4_V_fu_88;
        buffer_4_V_fu_88 <= buffer_5_V_fu_92;
        buffer_5_V_fu_92 <= buffer_6_V_fu_96;
        buffer_6_V_fu_96 <= buffer_7_V_fu_100;
        buffer_7_V_fu_100 <= buffer_8_V_fu_104;
        buffer_8_V_fu_104 <= buffer_9_V_fu_108;
        buffer_9_V_fu_108 <= buffer_10_V_fu_112;
        buffer_V_1_01066_fu_72 <= buffer_1_V_fu_76;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln700_13_reg_1491 <= add_ln700_13_fu_911_p2;
        add_ln700_29_reg_1496 <= add_ln700_29_fu_1001_p2;
        add_ln700_6_reg_1486 <= add_ln700_6_fu_873_p2;
        mul_ln895_reg_1511 <= mul_ln895_fu_1203_p2;
        ps_V_reg_1401_pp0_iter2_reg <= ps_V_reg_1401;
        ps_V_reg_1401_pp0_iter3_reg <= ps_V_reg_1401_pp0_iter2_reg;
        res_2_V_1_reg_1501 <= res_2_V_1_fu_1040_p3;
        ret_V_reg_1506 <= ret_V_fu_1197_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ps_V_reg_1401 <= ps_V_fu_394_p2;
        val_V_reg_1395 <= e_dout;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        detect_blk_n = detect_full_n;
    end else begin
        detect_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        detect_write = 1'b1;
    end else begin
        detect_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_blk_n = e_empty_n;
    end else begin
        e_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        e_read = 1'b1;
    end else begin
        e_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln215_1_fu_344_p2 = (zext_ln215_3_fu_314_p1 + zext_ln215_2_fu_310_p1);

assign add_ln215_2_fu_354_p2 = (zext_ln215_40_fu_340_p1 + zext_ln215_41_fu_350_p1);

assign add_ln215_3_fu_364_p2 = (zext_ln215_5_fu_322_p1 + zext_ln215_4_fu_318_p1);

assign add_ln215_4_fu_374_p2 = (zext_ln215_7_fu_330_p1 + zext_ln215_6_fu_326_p1);

assign add_ln215_5_fu_384_p2 = (zext_ln215_43_fu_370_p1 + zext_ln215_44_fu_380_p1);

assign add_ln215_fu_334_p2 = (zext_ln215_fu_302_p1 + zext_ln215_1_fu_306_p1);

assign add_ln700_12_fu_901_p2 = (zext_ln700_11_fu_895_p1 + zext_ln700_12_fu_898_p1);

assign add_ln700_13_fu_911_p2 = (zext_ln700_10_fu_891_p1 + zext_ln700_13_fu_907_p1);

assign add_ln700_14_fu_1013_p2 = (zext_ln700_7_fu_1007_p1 + zext_ln700_14_fu_1010_p1);

assign add_ln700_17_fu_923_p2 = (zext_ln700_15_fu_917_p1 + zext_ln700_16_fu_920_p1);

assign add_ln700_20_fu_939_p2 = (zext_ln700_18_fu_933_p1 + zext_ln700_19_fu_936_p1);

assign add_ln700_21_fu_949_p2 = (zext_ln700_17_fu_929_p1 + zext_ln700_20_fu_945_p1);

assign add_ln700_24_fu_965_p2 = (zext_ln700_22_fu_959_p1 + zext_ln700_23_fu_962_p1);

assign add_ln700_27_fu_981_p2 = (zext_ln700_25_fu_975_p1 + zext_ln700_26_fu_978_p1);

assign add_ln700_28_fu_991_p2 = (zext_ln700_24_fu_971_p1 + zext_ln700_27_fu_987_p1);

assign add_ln700_29_fu_1001_p2 = (zext_ln700_21_fu_955_p1 + zext_ln700_28_fu_997_p1);

assign add_ln700_2_fu_847_p2 = (zext_ln700_1_fu_841_p1 + zext_ln700_2_fu_844_p1);

assign add_ln700_30_fu_1019_p2 = (add_ln700_29_reg_1496 + add_ln700_14_fu_1013_p2);

assign add_ln700_5_fu_863_p2 = (zext_ln700_4_fu_857_p1 + zext_ln700_5_fu_860_p1);

assign add_ln700_6_fu_873_p2 = (zext_ln700_3_fu_853_p1 + zext_ln700_6_fu_869_p1);

assign add_ln700_9_fu_885_p2 = (zext_ln700_8_fu_879_p1 + zext_ln700_9_fu_882_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((detect_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((e_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((detect_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((e_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((detect_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((e_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (e_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter5 = (detect_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign detect_din = (icmp_ln895_fu_1057_p2 ^ 1'd1);

assign grp_fu_1069_p0 = zext_ln215_9_fu_414_p1;

assign grp_fu_1069_p1 = zext_ln215_9_fu_414_p1;

assign grp_fu_1069_p2 = grp_fu_1069_p20;

assign grp_fu_1069_p20 = mul_ln1352_fu_404_p2;

assign grp_fu_1077_p0 = zext_ln215_10_fu_418_p1;

assign grp_fu_1077_p1 = zext_ln215_10_fu_418_p1;

assign grp_fu_1077_p2 = grp_fu_1077_p20;

assign grp_fu_1077_p20 = mul_ln1352_3_fu_426_p2;

assign grp_fu_1085_p0 = zext_ln215_12_fu_436_p1;

assign grp_fu_1085_p1 = zext_ln215_12_fu_436_p1;

assign grp_fu_1085_p2 = grp_fu_1085_p20;

assign grp_fu_1085_p20 = mul_ln1352_5_fu_444_p2;

assign grp_fu_1093_p0 = zext_ln215_14_fu_454_p1;

assign grp_fu_1093_p1 = zext_ln215_14_fu_454_p1;

assign grp_fu_1093_p2 = grp_fu_1093_p20;

assign grp_fu_1093_p20 = mul_ln1352_7_fu_462_p2;

assign grp_fu_1101_p0 = zext_ln215_16_fu_472_p1;

assign grp_fu_1101_p1 = zext_ln215_16_fu_472_p1;

assign grp_fu_1101_p2 = grp_fu_1101_p20;

assign grp_fu_1101_p20 = mul_ln1352_9_fu_480_p2;

assign grp_fu_1109_p0 = zext_ln215_18_fu_490_p1;

assign grp_fu_1109_p1 = zext_ln215_18_fu_490_p1;

assign grp_fu_1109_p2 = grp_fu_1109_p20;

assign grp_fu_1109_p20 = mul_ln1352_11_fu_498_p2;

assign grp_fu_1117_p0 = zext_ln215_20_fu_508_p1;

assign grp_fu_1117_p1 = zext_ln215_20_fu_508_p1;

assign grp_fu_1117_p2 = grp_fu_1117_p20;

assign grp_fu_1117_p20 = mul_ln1352_13_fu_516_p2;

assign grp_fu_1125_p0 = zext_ln215_22_fu_526_p1;

assign grp_fu_1125_p1 = zext_ln215_22_fu_526_p1;

assign grp_fu_1125_p2 = grp_fu_1125_p20;

assign grp_fu_1125_p20 = mul_ln1352_15_fu_534_p2;

assign grp_fu_1133_p0 = zext_ln215_24_fu_544_p1;

assign grp_fu_1133_p1 = zext_ln215_24_fu_544_p1;

assign grp_fu_1133_p2 = grp_fu_1133_p20;

assign grp_fu_1133_p20 = mul_ln1352_17_fu_552_p2;

assign grp_fu_1141_p0 = zext_ln215_26_fu_562_p1;

assign grp_fu_1141_p1 = zext_ln215_26_fu_562_p1;

assign grp_fu_1141_p2 = grp_fu_1141_p20;

assign grp_fu_1141_p20 = mul_ln1352_19_fu_570_p2;

assign grp_fu_1149_p0 = zext_ln215_28_fu_580_p1;

assign grp_fu_1149_p1 = zext_ln215_28_fu_580_p1;

assign grp_fu_1149_p2 = grp_fu_1149_p20;

assign grp_fu_1149_p20 = mul_ln1352_21_fu_588_p2;

assign grp_fu_1157_p0 = zext_ln215_30_fu_598_p1;

assign grp_fu_1157_p1 = zext_ln215_30_fu_598_p1;

assign grp_fu_1157_p2 = grp_fu_1157_p20;

assign grp_fu_1157_p20 = mul_ln1352_23_fu_606_p2;

assign grp_fu_1165_p0 = zext_ln215_32_fu_616_p1;

assign grp_fu_1165_p1 = zext_ln215_32_fu_616_p1;

assign grp_fu_1165_p2 = grp_fu_1165_p20;

assign grp_fu_1165_p20 = mul_ln1352_25_fu_624_p2;

assign grp_fu_1173_p0 = zext_ln215_34_fu_634_p1;

assign grp_fu_1173_p1 = zext_ln215_34_fu_634_p1;

assign grp_fu_1173_p2 = grp_fu_1173_p20;

assign grp_fu_1173_p20 = mul_ln1352_27_fu_642_p2;

assign grp_fu_1181_p0 = zext_ln215_36_fu_652_p1;

assign grp_fu_1181_p1 = zext_ln215_36_fu_652_p1;

assign grp_fu_1181_p2 = grp_fu_1181_p20;

assign grp_fu_1181_p20 = mul_ln1352_29_fu_660_p2;

assign grp_fu_1189_p0 = zext_ln215_38_fu_670_p1;

assign grp_fu_1189_p1 = zext_ln215_38_fu_670_p1;

assign grp_fu_1189_p2 = grp_fu_1189_p20;

assign grp_fu_1189_p20 = mul_ln1352_31_fu_677_p2;

assign icmp_ln879_fu_1034_p2 = ((r_V_fu_1024_p4 == 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_1057_p2 = ((zext_ln895_1_fu_1054_p1 < mul_ln895_reg_1511) ? 1'b1 : 1'b0);

assign lhs_V_fu_1048_p1 = ps_V_reg_1401_pp0_iter3_reg;

assign mul_ln1352_11_fu_498_p0 = zext_ln215_19_fu_494_p1;

assign mul_ln1352_11_fu_498_p1 = zext_ln215_19_fu_494_p1;

assign mul_ln1352_11_fu_498_p2 = (mul_ln1352_11_fu_498_p0 * mul_ln1352_11_fu_498_p1);

assign mul_ln1352_13_fu_516_p0 = zext_ln215_21_fu_512_p1;

assign mul_ln1352_13_fu_516_p1 = zext_ln215_21_fu_512_p1;

assign mul_ln1352_13_fu_516_p2 = (mul_ln1352_13_fu_516_p0 * mul_ln1352_13_fu_516_p1);

assign mul_ln1352_15_fu_534_p0 = zext_ln215_23_fu_530_p1;

assign mul_ln1352_15_fu_534_p1 = zext_ln215_23_fu_530_p1;

assign mul_ln1352_15_fu_534_p2 = (mul_ln1352_15_fu_534_p0 * mul_ln1352_15_fu_534_p1);

assign mul_ln1352_17_fu_552_p0 = zext_ln215_25_fu_548_p1;

assign mul_ln1352_17_fu_552_p1 = zext_ln215_25_fu_548_p1;

assign mul_ln1352_17_fu_552_p2 = (mul_ln1352_17_fu_552_p0 * mul_ln1352_17_fu_552_p1);

assign mul_ln1352_19_fu_570_p0 = zext_ln215_27_fu_566_p1;

assign mul_ln1352_19_fu_570_p1 = zext_ln215_27_fu_566_p1;

assign mul_ln1352_19_fu_570_p2 = (mul_ln1352_19_fu_570_p0 * mul_ln1352_19_fu_570_p1);

assign mul_ln1352_21_fu_588_p0 = zext_ln215_29_fu_584_p1;

assign mul_ln1352_21_fu_588_p1 = zext_ln215_29_fu_584_p1;

assign mul_ln1352_21_fu_588_p2 = (mul_ln1352_21_fu_588_p0 * mul_ln1352_21_fu_588_p1);

assign mul_ln1352_23_fu_606_p0 = zext_ln215_31_fu_602_p1;

assign mul_ln1352_23_fu_606_p1 = zext_ln215_31_fu_602_p1;

assign mul_ln1352_23_fu_606_p2 = (mul_ln1352_23_fu_606_p0 * mul_ln1352_23_fu_606_p1);

assign mul_ln1352_25_fu_624_p0 = zext_ln215_33_fu_620_p1;

assign mul_ln1352_25_fu_624_p1 = zext_ln215_33_fu_620_p1;

assign mul_ln1352_25_fu_624_p2 = (mul_ln1352_25_fu_624_p0 * mul_ln1352_25_fu_624_p1);

assign mul_ln1352_27_fu_642_p0 = zext_ln215_35_fu_638_p1;

assign mul_ln1352_27_fu_642_p1 = zext_ln215_35_fu_638_p1;

assign mul_ln1352_27_fu_642_p2 = (mul_ln1352_27_fu_642_p0 * mul_ln1352_27_fu_642_p1);

assign mul_ln1352_29_fu_660_p0 = zext_ln215_37_fu_656_p1;

assign mul_ln1352_29_fu_660_p1 = zext_ln215_37_fu_656_p1;

assign mul_ln1352_29_fu_660_p2 = (mul_ln1352_29_fu_660_p0 * mul_ln1352_29_fu_660_p1);

assign mul_ln1352_31_fu_677_p0 = zext_ln215_39_fu_674_p1;

assign mul_ln1352_31_fu_677_p1 = zext_ln215_39_fu_674_p1;

assign mul_ln1352_31_fu_677_p2 = (mul_ln1352_31_fu_677_p0 * mul_ln1352_31_fu_677_p1);

assign mul_ln1352_3_fu_426_p0 = zext_ln215_11_fu_422_p1;

assign mul_ln1352_3_fu_426_p1 = zext_ln215_11_fu_422_p1;

assign mul_ln1352_3_fu_426_p2 = (mul_ln1352_3_fu_426_p0 * mul_ln1352_3_fu_426_p1);

assign mul_ln1352_5_fu_444_p0 = zext_ln215_13_fu_440_p1;

assign mul_ln1352_5_fu_444_p1 = zext_ln215_13_fu_440_p1;

assign mul_ln1352_5_fu_444_p2 = (mul_ln1352_5_fu_444_p0 * mul_ln1352_5_fu_444_p1);

assign mul_ln1352_7_fu_462_p0 = zext_ln215_15_fu_458_p1;

assign mul_ln1352_7_fu_462_p1 = zext_ln215_15_fu_458_p1;

assign mul_ln1352_7_fu_462_p2 = (mul_ln1352_7_fu_462_p0 * mul_ln1352_7_fu_462_p1);

assign mul_ln1352_9_fu_480_p0 = zext_ln215_17_fu_476_p1;

assign mul_ln1352_9_fu_480_p1 = zext_ln215_17_fu_476_p1;

assign mul_ln1352_9_fu_480_p2 = (mul_ln1352_9_fu_480_p0 * mul_ln1352_9_fu_480_p1);

assign mul_ln1352_fu_404_p0 = zext_ln215_8_fu_400_p1;

assign mul_ln1352_fu_404_p1 = zext_ln215_8_fu_400_p1;

assign mul_ln1352_fu_404_p2 = (mul_ln1352_fu_404_p0 * mul_ln1352_fu_404_p1);

assign mul_ln895_fu_1203_p0 = mul_ln895_fu_1203_p00;

assign mul_ln895_fu_1203_p00 = res_2_V_1_reg_1501;

assign mul_ln895_fu_1203_p1 = 27'd27;

assign ps_V_fu_394_p2 = (zext_ln215_42_fu_360_p1 + zext_ln215_45_fu_390_p1);

assign r_V_fu_1024_p4 = {{add_ln700_30_fu_1019_p2[18:2]}};

assign res_2_V_1_fu_1040_p3 = ((icmp_ln879_fu_1034_p2[0:0] === 1'b1) ? 17'd31 : r_V_fu_1024_p4);

assign ret_V_fu_1197_p0 = lhs_V_fu_1048_p1;

assign ret_V_fu_1197_p1 = lhs_V_fu_1048_p1;

assign zext_ln215_10_fu_418_p1 = buffer_2_V_fu_80;

assign zext_ln215_11_fu_422_p1 = buffer_3_V_fu_84;

assign zext_ln215_12_fu_436_p1 = buffer_4_V_fu_88;

assign zext_ln215_13_fu_440_p1 = buffer_5_V_fu_92;

assign zext_ln215_14_fu_454_p1 = buffer_6_V_fu_96;

assign zext_ln215_15_fu_458_p1 = buffer_7_V_fu_100;

assign zext_ln215_16_fu_472_p1 = buffer_8_V_fu_104;

assign zext_ln215_17_fu_476_p1 = buffer_9_V_fu_108;

assign zext_ln215_18_fu_490_p1 = buffer_10_V_fu_112;

assign zext_ln215_19_fu_494_p1 = buffer_11_V_fu_116;

assign zext_ln215_1_fu_306_p1 = buffer_1_V_fu_76;

assign zext_ln215_20_fu_508_p1 = buffer_12_V_fu_120;

assign zext_ln215_21_fu_512_p1 = buffer_13_V_fu_124;

assign zext_ln215_22_fu_526_p1 = buffer_14_V_fu_128;

assign zext_ln215_23_fu_530_p1 = buffer_15_V_fu_132;

assign zext_ln215_24_fu_544_p1 = buffer_16_V_fu_136;

assign zext_ln215_25_fu_548_p1 = buffer_17_V_fu_140;

assign zext_ln215_26_fu_562_p1 = buffer_18_V_fu_144;

assign zext_ln215_27_fu_566_p1 = buffer_19_V_fu_148;

assign zext_ln215_28_fu_580_p1 = buffer_20_V_fu_152;

assign zext_ln215_29_fu_584_p1 = buffer_21_V_fu_156;

assign zext_ln215_2_fu_310_p1 = buffer_4_V_fu_88;

assign zext_ln215_30_fu_598_p1 = buffer_22_V_fu_160;

assign zext_ln215_31_fu_602_p1 = buffer_23_V_fu_164;

assign zext_ln215_32_fu_616_p1 = buffer_24_V_fu_168;

assign zext_ln215_33_fu_620_p1 = buffer_25_V_fu_172;

assign zext_ln215_34_fu_634_p1 = buffer_26_V_fu_176;

assign zext_ln215_35_fu_638_p1 = buffer_27_V_fu_180;

assign zext_ln215_36_fu_652_p1 = buffer_28_V_fu_184;

assign zext_ln215_37_fu_656_p1 = buffer_29_V_fu_188;

assign zext_ln215_38_fu_670_p1 = buffer_30_V_fu_192;

assign zext_ln215_39_fu_674_p1 = val_V_reg_1395;

assign zext_ln215_3_fu_314_p1 = buffer_5_V_fu_92;

assign zext_ln215_40_fu_340_p1 = add_ln215_fu_334_p2;

assign zext_ln215_41_fu_350_p1 = add_ln215_1_fu_344_p2;

assign zext_ln215_42_fu_360_p1 = add_ln215_2_fu_354_p2;

assign zext_ln215_43_fu_370_p1 = add_ln215_3_fu_364_p2;

assign zext_ln215_44_fu_380_p1 = add_ln215_4_fu_374_p2;

assign zext_ln215_45_fu_390_p1 = add_ln215_5_fu_384_p2;

assign zext_ln215_4_fu_318_p1 = buffer_14_V_fu_128;

assign zext_ln215_5_fu_322_p1 = buffer_15_V_fu_132;

assign zext_ln215_6_fu_326_p1 = buffer_18_V_fu_144;

assign zext_ln215_7_fu_330_p1 = buffer_19_V_fu_148;

assign zext_ln215_8_fu_400_p1 = buffer_V_1_01066_fu_72;

assign zext_ln215_9_fu_414_p1 = buffer_1_V_fu_76;

assign zext_ln215_fu_302_p1 = buffer_V_1_01066_fu_72;

assign zext_ln700_10_fu_891_p1 = add_ln700_9_fu_885_p2;

assign zext_ln700_11_fu_895_p1 = add_ln700_10_reg_1436;

assign zext_ln700_12_fu_898_p1 = add_ln700_11_reg_1441;

assign zext_ln700_13_fu_907_p1 = add_ln700_12_fu_901_p2;

assign zext_ln700_14_fu_1010_p1 = add_ln700_13_reg_1491;

assign zext_ln700_15_fu_917_p1 = add_ln700_15_reg_1446;

assign zext_ln700_16_fu_920_p1 = add_ln700_16_reg_1451;

assign zext_ln700_17_fu_929_p1 = add_ln700_17_fu_923_p2;

assign zext_ln700_18_fu_933_p1 = add_ln700_18_reg_1456;

assign zext_ln700_19_fu_936_p1 = add_ln700_19_reg_1461;

assign zext_ln700_1_fu_841_p1 = add_ln700_reg_1406;

assign zext_ln700_20_fu_945_p1 = add_ln700_20_fu_939_p2;

assign zext_ln700_21_fu_955_p1 = add_ln700_21_fu_949_p2;

assign zext_ln700_22_fu_959_p1 = add_ln700_22_reg_1466;

assign zext_ln700_23_fu_962_p1 = add_ln700_23_reg_1471;

assign zext_ln700_24_fu_971_p1 = add_ln700_24_fu_965_p2;

assign zext_ln700_25_fu_975_p1 = add_ln700_25_reg_1476;

assign zext_ln700_26_fu_978_p1 = add_ln700_26_reg_1481;

assign zext_ln700_27_fu_987_p1 = add_ln700_27_fu_981_p2;

assign zext_ln700_28_fu_997_p1 = add_ln700_28_fu_991_p2;

assign zext_ln700_2_fu_844_p1 = add_ln700_1_reg_1411;

assign zext_ln700_3_fu_853_p1 = add_ln700_2_fu_847_p2;

assign zext_ln700_4_fu_857_p1 = add_ln700_3_reg_1416;

assign zext_ln700_5_fu_860_p1 = add_ln700_4_reg_1421;

assign zext_ln700_6_fu_869_p1 = add_ln700_5_fu_863_p2;

assign zext_ln700_7_fu_1007_p1 = add_ln700_6_reg_1486;

assign zext_ln700_8_fu_879_p1 = add_ln700_7_reg_1426;

assign zext_ln700_9_fu_882_p1 = add_ln700_8_reg_1431;

assign zext_ln895_1_fu_1054_p1 = ret_V_reg_1506;

endmodule //Seuil_calc1_do_gen
