// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="my_module,hls_ip_2020_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.955000,HLS_SYN_LAT=581,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=181,HLS_SYN_FF=22058,HLS_SYN_LUT=21399,HLS_VERSION=2020_1}" *)

module my_module (
        clock,
        reset,
        e_dout,
        e_empty_n,
        e_read,
        addr_din,
        addr_full_n,
        addr_write,
        rgbv_din,
        rgbv_full_n,
        rgbv_write
);


input   clock;
input   reset;
input  [7:0] e_dout;
input   e_empty_n;
output   e_read;
output  [31:0] addr_din;
input   addr_full_n;
output   addr_write;
output  [23:0] rgbv_din;
input   rgbv_full_n;
output   rgbv_write;

wire    grp_ModuleCompute_fu_212_e_read;
wire   [7:0] grp_ModuleCompute_fu_212_s_din;
wire    grp_ModuleCompute_fu_212_s_write;
wire    grp_Detecteur_fu_226_e_read;
wire   [7:0] grp_Detecteur_fu_226_s_din;
wire    grp_Detecteur_fu_226_s_write;
wire    grp_DownSampling_fu_278_e_read;
wire   [7:0] grp_DownSampling_fu_278_s_din;
wire    grp_DownSampling_fu_278_s_write;
wire    grp_BitDecider_fu_292_e_read;
wire   [0:0] grp_BitDecider_fu_292_s_din;
wire    grp_BitDecider_fu_292_s_write;
wire    grp_BitsToBytes_fu_306_e_read;
wire   [7:0] grp_BitsToBytes_fu_306_s_din;
wire    grp_BitsToBytes_fu_306_s_write;
wire    grp_CRCCheck_fu_320_e_read;
wire   [7:0] grp_CRCCheck_fu_320_s_din;
wire    grp_CRCCheck_fu_320_s_write;
wire    grp_FrameProcessing_fu_334_e_read;
wire   [31:0] grp_FrameProcessing_fu_334_addr_din;
wire    grp_FrameProcessing_fu_334_addr_write;
wire   [23:0] grp_FrameProcessing_fu_334_rgbv_din;
wire    grp_FrameProcessing_fu_334_rgbv_write;
wire    mod2dbl_1_full_n;
wire   [7:0] mod2dbl_1_dout;
wire    mod2dbl_1_empty_n;
wire    det2dow_1_full_n;
wire   [7:0] det2dow_1_dout;
wire    det2dow_1_empty_n;
wire    dow2bit_1_full_n;
wire   [7:0] dow2bit_1_dout;
wire    dow2bit_1_empty_n;
wire    bit2byt_1_full_n;
wire   [0:0] bit2byt_1_dout;
wire    bit2byt_1_empty_n;
wire    byt2crc_1_full_n;
wire   [7:0] byt2crc_1_dout;
wire    byt2crc_1_empty_n;
wire    crc2fra_1_full_n;
wire   [7:0] crc2fra_1_dout;
wire    crc2fra_1_empty_n;

ModuleCompute grp_ModuleCompute_fu_212(
    .e_dout(e_dout),
    .e_empty_n(e_empty_n),
    .e_read(grp_ModuleCompute_fu_212_e_read),
    .s_din(grp_ModuleCompute_fu_212_s_din),
    .s_full_n(mod2dbl_1_full_n),
    .s_write(grp_ModuleCompute_fu_212_s_write),
    .clock(clock),
    .reset(reset)
);

Detecteur grp_Detecteur_fu_226(
    .e_dout(mod2dbl_1_dout),
    .e_empty_n(mod2dbl_1_empty_n),
    .e_read(grp_Detecteur_fu_226_e_read),
    .s_din(grp_Detecteur_fu_226_s_din),
    .s_full_n(det2dow_1_full_n),
    .s_write(grp_Detecteur_fu_226_s_write),
    .clock(clock),
    .reset(reset)
);

DownSampling grp_DownSampling_fu_278(
    .e_dout(det2dow_1_dout),
    .e_empty_n(det2dow_1_empty_n),
    .e_read(grp_DownSampling_fu_278_e_read),
    .s_din(grp_DownSampling_fu_278_s_din),
    .s_full_n(dow2bit_1_full_n),
    .s_write(grp_DownSampling_fu_278_s_write),
    .clock(clock),
    .reset(reset)
);

BitDecider grp_BitDecider_fu_292(
    .e_dout(dow2bit_1_dout),
    .e_empty_n(dow2bit_1_empty_n),
    .e_read(grp_BitDecider_fu_292_e_read),
    .s_din(grp_BitDecider_fu_292_s_din),
    .s_full_n(bit2byt_1_full_n),
    .s_write(grp_BitDecider_fu_292_s_write),
    .clock(clock),
    .reset(reset)
);

BitsToBytes grp_BitsToBytes_fu_306(
    .e_dout(bit2byt_1_dout),
    .e_empty_n(bit2byt_1_empty_n),
    .e_read(grp_BitsToBytes_fu_306_e_read),
    .s_din(grp_BitsToBytes_fu_306_s_din),
    .s_full_n(byt2crc_1_full_n),
    .s_write(grp_BitsToBytes_fu_306_s_write),
    .clock(clock),
    .reset(reset)
);

CRCCheck grp_CRCCheck_fu_320(
    .e_dout(byt2crc_1_dout),
    .e_empty_n(byt2crc_1_empty_n),
    .e_read(grp_CRCCheck_fu_320_e_read),
    .s_din(grp_CRCCheck_fu_320_s_din),
    .s_full_n(crc2fra_1_full_n),
    .s_write(grp_CRCCheck_fu_320_s_write),
    .clock(clock),
    .reset(reset)
);

FrameProcessing grp_FrameProcessing_fu_334(
    .e_dout(crc2fra_1_dout),
    .e_empty_n(crc2fra_1_empty_n),
    .e_read(grp_FrameProcessing_fu_334_e_read),
    .addr_din(grp_FrameProcessing_fu_334_addr_din),
    .addr_full_n(addr_full_n),
    .addr_write(grp_FrameProcessing_fu_334_addr_write),
    .rgbv_din(grp_FrameProcessing_fu_334_rgbv_din),
    .rgbv_full_n(rgbv_full_n),
    .rgbv_write(grp_FrameProcessing_fu_334_rgbv_write),
    .clock(clock),
    .reset(reset)
);

fifo_w8_d1024_A_x mod2dbl_1_fifo_U(
    .clk(clock),
    .reset(reset),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_ModuleCompute_fu_212_s_din),
    .if_full_n(mod2dbl_1_full_n),
    .if_write(grp_ModuleCompute_fu_212_s_write),
    .if_dout(mod2dbl_1_dout),
    .if_empty_n(mod2dbl_1_empty_n),
    .if_read(grp_Detecteur_fu_226_e_read)
);

fifo_w8_d32_A det2dow_1_fifo_U(
    .clk(clock),
    .reset(reset),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_Detecteur_fu_226_s_din),
    .if_full_n(det2dow_1_full_n),
    .if_write(grp_Detecteur_fu_226_s_write),
    .if_dout(det2dow_1_dout),
    .if_empty_n(det2dow_1_empty_n),
    .if_read(grp_DownSampling_fu_278_e_read)
);

fifo_w8_d32_A dow2bit_1_fifo_U(
    .clk(clock),
    .reset(reset),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_DownSampling_fu_278_s_din),
    .if_full_n(dow2bit_1_full_n),
    .if_write(grp_DownSampling_fu_278_s_write),
    .if_dout(dow2bit_1_dout),
    .if_empty_n(dow2bit_1_empty_n),
    .if_read(grp_BitDecider_fu_292_e_read)
);

fifo_w1_d32_A bit2byt_1_fifo_U(
    .clk(clock),
    .reset(reset),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_BitDecider_fu_292_s_din),
    .if_full_n(bit2byt_1_full_n),
    .if_write(grp_BitDecider_fu_292_s_write),
    .if_dout(bit2byt_1_dout),
    .if_empty_n(bit2byt_1_empty_n),
    .if_read(grp_BitsToBytes_fu_306_e_read)
);

fifo_w8_d32_A byt2crc_1_fifo_U(
    .clk(clock),
    .reset(reset),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_BitsToBytes_fu_306_s_din),
    .if_full_n(byt2crc_1_full_n),
    .if_write(grp_BitsToBytes_fu_306_s_write),
    .if_dout(byt2crc_1_dout),
    .if_empty_n(byt2crc_1_empty_n),
    .if_read(grp_CRCCheck_fu_320_e_read)
);

fifo_w8_d32_A crc2fra_1_fifo_U(
    .clk(clock),
    .reset(reset),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_CRCCheck_fu_320_s_din),
    .if_full_n(crc2fra_1_full_n),
    .if_write(grp_CRCCheck_fu_320_s_write),
    .if_dout(crc2fra_1_dout),
    .if_empty_n(crc2fra_1_empty_n),
    .if_read(grp_FrameProcessing_fu_334_e_read)
);

assign addr_din = grp_FrameProcessing_fu_334_addr_din;

assign addr_write = grp_FrameProcessing_fu_334_addr_write;

assign e_read = grp_ModuleCompute_fu_212_e_read;

assign rgbv_din = grp_FrameProcessing_fu_334_rgbv_din;

assign rgbv_write = grp_FrameProcessing_fu_334_rgbv_write;

endmodule //my_module
