// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CRCCheck,hls_ip_2020_1,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100t-csg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.955000,HLS_SYN_LAT=60,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=218,HLS_SYN_LUT=890,HLS_VERSION=2020_1}" *)

module CRCCheck (
        clock,
        reset,
        e_dout,
        e_empty_n,
        e_read,
        s_din,
        s_full_n,
        s_write
);


input   clock;
input   reset;
input  [7:0] e_dout;
input   e_empty_n;
output   e_read;
output  [7:0] s_din;
input   s_full_n;
output   s_write;

wire    grp_CRCCheck_do_gen_fu_56_e_read;
wire   [7:0] grp_CRCCheck_do_gen_fu_56_s_din;
wire    grp_CRCCheck_do_gen_fu_56_s_write;

CRCCheck_do_gen grp_CRCCheck_do_gen_fu_56(
    .ap_clk(clock),
    .ap_rst(reset),
    .e_dout(e_dout),
    .e_empty_n(e_empty_n),
    .e_read(grp_CRCCheck_do_gen_fu_56_e_read),
    .s_din(grp_CRCCheck_do_gen_fu_56_s_din),
    .s_full_n(s_full_n),
    .s_write(grp_CRCCheck_do_gen_fu_56_s_write)
);

assign e_read = grp_CRCCheck_do_gen_fu_56_e_read;

assign s_din = grp_CRCCheck_do_gen_fu_56_s_din;

assign s_write = grp_CRCCheck_do_gen_fu_56_s_write;

endmodule //CRCCheck
