// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _DOUBLEUR_U_HH_
#define _DOUBLEUR_U_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "DOUBLEUR_U_do_gen.h"

namespace ap_rtl {

struct DOUBLEUR_U : public sc_module {
    // Port declarations 11
    sc_in_clk clock;
    sc_in< sc_logic > reset;
    sc_in< sc_lv<8> > e_dout;
    sc_in< sc_logic > e_empty_n;
    sc_out< sc_logic > e_read;
    sc_out< sc_lv<8> > s1_din;
    sc_in< sc_logic > s1_full_n;
    sc_out< sc_logic > s1_write;
    sc_out< sc_lv<8> > s2_din;
    sc_in< sc_logic > s2_full_n;
    sc_out< sc_logic > s2_write;


    // Module declarations
    DOUBLEUR_U(sc_module_name name);
    SC_HAS_PROCESS(DOUBLEUR_U);

    ~DOUBLEUR_U();

    sc_trace_file* mVcdFile;

    DOUBLEUR_U_do_gen* grp_DOUBLEUR_U_do_gen_fu_60;
    sc_signal< sc_logic > grp_DOUBLEUR_U_do_gen_fu_60_e_read;
    sc_signal< sc_lv<8> > grp_DOUBLEUR_U_do_gen_fu_60_s1_din;
    sc_signal< sc_logic > grp_DOUBLEUR_U_do_gen_fu_60_s1_write;
    sc_signal< sc_lv<8> > grp_DOUBLEUR_U_do_gen_fu_60_s2_din;
    sc_signal< sc_logic > grp_DOUBLEUR_U_do_gen_fu_60_s2_write;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_e_read();
    void thread_s1_din();
    void thread_s1_write();
    void thread_s2_din();
    void thread_s2_write();
};

}

using namespace ap_rtl;

#endif
