// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "FrameProcessing_do_gen.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic FrameProcessing_do_gen::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic FrameProcessing_do_gen::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state2 = "10";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state3 = "100";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state4 = "1000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state5 = "10000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state6 = "100000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state7 = "1000000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state8 = "10000000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state9 = "100000000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state10 = "1000000000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state11 = "10000000000";
const sc_lv<12> FrameProcessing_do_gen::ap_ST_fsm_state12 = "100000000000";
const bool FrameProcessing_do_gen::ap_const_boolean_1 = true;
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_1 = "1";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_2 = "10";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_3 = "11";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_4 = "100";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_5 = "101";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_6 = "110";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_7 = "111";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_8 = "1000";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_9 = "1001";
const sc_lv<1> FrameProcessing_do_gen::ap_const_lv1_1 = "1";
const sc_lv<1> FrameProcessing_do_gen::ap_const_lv1_0 = "0";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_A = "1010";
const sc_lv<32> FrameProcessing_do_gen::ap_const_lv32_B = "1011";
const sc_lv<7> FrameProcessing_do_gen::ap_const_lv7_0 = "0000000";
const sc_lv<6> FrameProcessing_do_gen::ap_const_lv6_0 = "000000";
const sc_lv<16> FrameProcessing_do_gen::ap_const_lv16_22 = "100010";
const sc_lv<16> FrameProcessing_do_gen::ap_const_lv16_33 = "110011";
const sc_lv<16> FrameProcessing_do_gen::ap_const_lv16_11 = "10001";
const sc_lv<9> FrameProcessing_do_gen::ap_const_lv9_0 = "000000000";
const sc_lv<16> FrameProcessing_do_gen::ap_const_lv16_14 = "10100";
const sc_lv<7> FrameProcessing_do_gen::ap_const_lv7_40 = "1000000";
const sc_lv<7> FrameProcessing_do_gen::ap_const_lv7_1 = "1";
const sc_lv<26> FrameProcessing_do_gen::ap_const_lv26_1 = "1";
const sc_lv<6> FrameProcessing_do_gen::ap_const_lv6_3C = "111100";
const sc_lv<6> FrameProcessing_do_gen::ap_const_lv6_1 = "1";

FrameProcessing_do_gen::FrameProcessing_do_gen(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln103_fu_232_p2);
    sensitive << ( zext_ln103_fu_204_p1 );
    sensitive << ( zext_ln103_1_fu_216_p1 );

    SC_METHOD(thread_add_ln107_1_fu_273_p2);
    sensitive << ( p_shl2_fu_264_p4 );
    sensitive << ( p_shl_fu_253_p3 );

    SC_METHOD(thread_add_ln107_2_fu_279_p2);
    sensitive << ( add_ln107_fu_244_p2 );
    sensitive << ( add_ln107_1_fu_273_p2 );

    SC_METHOD(thread_add_ln107_fu_244_p2);
    sensitive << ( mot1_fu_180_p3 );

    SC_METHOD(thread_addr_blk_n);
    sensitive << ( addr_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_addr_din);
    sensitive << ( e_empty_n );
    sensitive << ( addr_full_n );
    sensitive << ( rgbv_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( v_assign_cast_reg_406 );

    SC_METHOD(thread_addr_write);
    sensitive << ( e_empty_n );
    sensitive << ( addr_full_n );
    sensitive << ( rgbv_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state10);
    sensitive << ( e_empty_n );
    sensitive << ( ap_predicate_op70_read_state10 );
    sensitive << ( ap_predicate_op79_read_state10 );
    sensitive << ( ap_predicate_op88_read_state10 );
    sensitive << ( ap_predicate_op97_read_state10 );

    SC_METHOD(thread_ap_block_state12);
    sensitive << ( e_empty_n );
    sensitive << ( addr_full_n );
    sensitive << ( rgbv_full_n );

    SC_METHOD(thread_ap_predicate_op70_read_state10);
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( icmp_ln96_reg_384 );
    sensitive << ( icmp_ln124_fu_285_p2 );

    SC_METHOD(thread_ap_predicate_op79_read_state10);
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( icmp_ln96_reg_384 );
    sensitive << ( icmp_ln107_fu_305_p2 );

    SC_METHOD(thread_ap_predicate_op88_read_state10);
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( icmp_ln70_fu_316_p2 );

    SC_METHOD(thread_ap_predicate_op97_read_state10);
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln57_fu_328_p2 );

    SC_METHOD(thread_curr_off_1_fu_310_p2);
    sensitive << ( v_assign_reg_133 );

    SC_METHOD(thread_curr_off_fu_238_p2);
    sensitive << ( zext_ln103_2_fu_228_p1 );
    sensitive << ( add_ln103_fu_232_p2 );

    SC_METHOD(thread_e_blk_n);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln57_fu_328_p2 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( icmp_ln70_fu_316_p2 );
    sensitive << ( icmp_ln96_reg_384 );
    sensitive << ( icmp_ln107_fu_305_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln124_fu_285_p2 );

    SC_METHOD(thread_e_read);
    sensitive << ( e_empty_n );
    sensitive << ( addr_full_n );
    sensitive << ( rgbv_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_predicate_op70_read_state10 );
    sensitive << ( ap_predicate_op79_read_state10 );
    sensitive << ( ap_predicate_op88_read_state10 );
    sensitive << ( ap_predicate_op97_read_state10 );

    SC_METHOD(thread_i_3_fu_322_p2);
    sensitive << ( i1_0_reg_142 );

    SC_METHOD(thread_i_4_fu_291_p2);
    sensitive << ( i3_0_reg_122 );

    SC_METHOD(thread_i_fu_334_p2);
    sensitive << ( i_0_reg_153 );

    SC_METHOD(thread_icmp_ln107_fu_305_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( icmp_ln96_reg_384 );
    sensitive << ( ap_predicate_op70_read_state10 );
    sensitive << ( ap_predicate_op79_read_state10 );
    sensitive << ( ap_predicate_op88_read_state10 );
    sensitive << ( ap_predicate_op97_read_state10 );
    sensitive << ( add_ln107_2_reg_393 );
    sensitive << ( trunc_ln107_2_fu_301_p1 );

    SC_METHOD(thread_icmp_ln124_fu_285_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( icmp_ln96_reg_384 );
    sensitive << ( ap_predicate_op70_read_state10 );
    sensitive << ( ap_predicate_op79_read_state10 );
    sensitive << ( ap_predicate_op88_read_state10 );
    sensitive << ( ap_predicate_op97_read_state10 );
    sensitive << ( i3_0_reg_122 );

    SC_METHOD(thread_icmp_ln51_fu_186_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( type_fu_172_p3 );

    SC_METHOD(thread_icmp_ln57_fu_328_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( ap_predicate_op70_read_state10 );
    sensitive << ( ap_predicate_op79_read_state10 );
    sensitive << ( ap_predicate_op88_read_state10 );
    sensitive << ( ap_predicate_op97_read_state10 );
    sensitive << ( i_0_reg_153 );

    SC_METHOD(thread_icmp_ln60_fu_192_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln51_fu_186_p2 );
    sensitive << ( type_fu_172_p3 );

    SC_METHOD(thread_icmp_ln70_fu_316_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( ap_predicate_op70_read_state10 );
    sensitive << ( ap_predicate_op79_read_state10 );
    sensitive << ( ap_predicate_op88_read_state10 );
    sensitive << ( ap_predicate_op97_read_state10 );
    sensitive << ( i1_0_reg_142 );

    SC_METHOD(thread_icmp_ln96_fu_198_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln51_fu_186_p2 );
    sensitive << ( icmp_ln60_fu_192_p2 );
    sensitive << ( type_fu_172_p3 );

    SC_METHOD(thread_mot1_fu_180_p3);
    sensitive << ( val_V_5_reg_351 );
    sensitive << ( val_V_6_reg_356 );

    SC_METHOD(thread_p_shl2_fu_264_p4);
    sensitive << ( val_V_7_reg_361 );
    sensitive << ( trunc_ln107_1_fu_261_p1 );

    SC_METHOD(thread_p_shl_fu_253_p3);
    sensitive << ( trunc_ln107_fu_250_p1 );

    SC_METHOD(thread_rgbv_blk_n);
    sensitive << ( rgbv_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_rgbv_din);
    sensitive << ( e_dout );
    sensitive << ( e_empty_n );
    sensitive << ( addr_full_n );
    sensitive << ( rgbv_full_n );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( reg_164 );
    sensitive << ( reg_168 );

    SC_METHOD(thread_rgbv_write);
    sensitive << ( e_empty_n );
    sensitive << ( addr_full_n );
    sensitive << ( rgbv_full_n );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_shl_ln103_1_fu_220_p4);
    sensitive << ( val_V_7_reg_361 );
    sensitive << ( val_V_8_reg_369 );

    SC_METHOD(thread_shl_ln_fu_208_p4);
    sensitive << ( val_V_7_reg_361 );
    sensitive << ( val_V_8_reg_369 );

    SC_METHOD(thread_trunc_ln107_1_fu_261_p1);
    sensitive << ( val_V_8_reg_369 );

    SC_METHOD(thread_trunc_ln107_2_fu_301_p1);
    sensitive << ( v_assign_reg_133 );

    SC_METHOD(thread_trunc_ln107_fu_250_p1);
    sensitive << ( val_V_7_reg_361 );

    SC_METHOD(thread_type_fu_172_p3);
    sensitive << ( reg_164 );
    sensitive << ( reg_168 );

    SC_METHOD(thread_v_assign_cast_fu_297_p1);
    sensitive << ( v_assign_reg_133 );

    SC_METHOD(thread_zext_ln103_1_fu_216_p1);
    sensitive << ( shl_ln_fu_208_p4 );

    SC_METHOD(thread_zext_ln103_2_fu_228_p1);
    sensitive << ( shl_ln103_1_fu_220_p4 );

    SC_METHOD(thread_zext_ln103_fu_204_p1);
    sensitive << ( mot1_fu_180_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( e_empty_n );
    sensitive << ( addr_full_n );
    sensitive << ( rgbv_full_n );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln51_reg_376 );
    sensitive << ( icmp_ln57_fu_328_p2 );
    sensitive << ( icmp_ln60_reg_380 );
    sensitive << ( icmp_ln70_fu_316_p2 );
    sensitive << ( icmp_ln96_reg_384 );
    sensitive << ( icmp_ln107_fu_305_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln124_fu_285_p2 );
    sensitive << ( ap_predicate_op70_read_state10 );
    sensitive << ( ap_predicate_op79_read_state10 );
    sensitive << ( ap_predicate_op88_read_state10 );
    sensitive << ( ap_predicate_op97_read_state10 );

    ap_CS_fsm = "000000000010";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "FrameProcessing_do_gen_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, e_dout, "(port)e_dout");
    sc_trace(mVcdFile, e_empty_n, "(port)e_empty_n");
    sc_trace(mVcdFile, e_read, "(port)e_read");
    sc_trace(mVcdFile, addr_din, "(port)addr_din");
    sc_trace(mVcdFile, addr_full_n, "(port)addr_full_n");
    sc_trace(mVcdFile, addr_write, "(port)addr_write");
    sc_trace(mVcdFile, rgbv_din, "(port)rgbv_din");
    sc_trace(mVcdFile, rgbv_full_n, "(port)rgbv_full_n");
    sc_trace(mVcdFile, rgbv_write, "(port)rgbv_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, e_blk_n, "e_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, icmp_ln51_reg_376, "icmp_ln51_reg_376");
    sc_trace(mVcdFile, icmp_ln57_fu_328_p2, "icmp_ln57_fu_328_p2");
    sc_trace(mVcdFile, icmp_ln60_reg_380, "icmp_ln60_reg_380");
    sc_trace(mVcdFile, icmp_ln70_fu_316_p2, "icmp_ln70_fu_316_p2");
    sc_trace(mVcdFile, icmp_ln96_reg_384, "icmp_ln96_reg_384");
    sc_trace(mVcdFile, icmp_ln107_fu_305_p2, "icmp_ln107_fu_305_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, icmp_ln124_fu_285_p2, "icmp_ln124_fu_285_p2");
    sc_trace(mVcdFile, addr_blk_n, "addr_blk_n");
    sc_trace(mVcdFile, rgbv_blk_n, "rgbv_blk_n");
    sc_trace(mVcdFile, reg_164, "reg_164");
    sc_trace(mVcdFile, ap_predicate_op70_read_state10, "ap_predicate_op70_read_state10");
    sc_trace(mVcdFile, ap_predicate_op79_read_state10, "ap_predicate_op79_read_state10");
    sc_trace(mVcdFile, ap_predicate_op88_read_state10, "ap_predicate_op88_read_state10");
    sc_trace(mVcdFile, ap_predicate_op97_read_state10, "ap_predicate_op97_read_state10");
    sc_trace(mVcdFile, ap_block_state10, "ap_block_state10");
    sc_trace(mVcdFile, reg_168, "reg_168");
    sc_trace(mVcdFile, val_V_5_reg_351, "val_V_5_reg_351");
    sc_trace(mVcdFile, val_V_6_reg_356, "val_V_6_reg_356");
    sc_trace(mVcdFile, val_V_7_reg_361, "val_V_7_reg_361");
    sc_trace(mVcdFile, val_V_8_reg_369, "val_V_8_reg_369");
    sc_trace(mVcdFile, icmp_ln51_fu_186_p2, "icmp_ln51_fu_186_p2");
    sc_trace(mVcdFile, icmp_ln60_fu_192_p2, "icmp_ln60_fu_192_p2");
    sc_trace(mVcdFile, icmp_ln96_fu_198_p2, "icmp_ln96_fu_198_p2");
    sc_trace(mVcdFile, curr_off_fu_238_p2, "curr_off_fu_238_p2");
    sc_trace(mVcdFile, add_ln107_2_fu_279_p2, "add_ln107_2_fu_279_p2");
    sc_trace(mVcdFile, add_ln107_2_reg_393, "add_ln107_2_reg_393");
    sc_trace(mVcdFile, i_4_fu_291_p2, "i_4_fu_291_p2");
    sc_trace(mVcdFile, v_assign_cast_fu_297_p1, "v_assign_cast_fu_297_p1");
    sc_trace(mVcdFile, v_assign_cast_reg_406, "v_assign_cast_reg_406");
    sc_trace(mVcdFile, curr_off_1_fu_310_p2, "curr_off_1_fu_310_p2");
    sc_trace(mVcdFile, curr_off_1_reg_414, "curr_off_1_reg_414");
    sc_trace(mVcdFile, i_3_fu_322_p2, "i_3_fu_322_p2");
    sc_trace(mVcdFile, i_fu_334_p2, "i_fu_334_p2");
    sc_trace(mVcdFile, i3_0_reg_122, "i3_0_reg_122");
    sc_trace(mVcdFile, v_assign_reg_133, "v_assign_reg_133");
    sc_trace(mVcdFile, ap_block_state12, "ap_block_state12");
    sc_trace(mVcdFile, i1_0_reg_142, "i1_0_reg_142");
    sc_trace(mVcdFile, i_0_reg_153, "i_0_reg_153");
    sc_trace(mVcdFile, type_fu_172_p3, "type_fu_172_p3");
    sc_trace(mVcdFile, mot1_fu_180_p3, "mot1_fu_180_p3");
    sc_trace(mVcdFile, shl_ln_fu_208_p4, "shl_ln_fu_208_p4");
    sc_trace(mVcdFile, shl_ln103_1_fu_220_p4, "shl_ln103_1_fu_220_p4");
    sc_trace(mVcdFile, zext_ln103_fu_204_p1, "zext_ln103_fu_204_p1");
    sc_trace(mVcdFile, zext_ln103_1_fu_216_p1, "zext_ln103_1_fu_216_p1");
    sc_trace(mVcdFile, zext_ln103_2_fu_228_p1, "zext_ln103_2_fu_228_p1");
    sc_trace(mVcdFile, add_ln103_fu_232_p2, "add_ln103_fu_232_p2");
    sc_trace(mVcdFile, trunc_ln107_fu_250_p1, "trunc_ln107_fu_250_p1");
    sc_trace(mVcdFile, trunc_ln107_1_fu_261_p1, "trunc_ln107_1_fu_261_p1");
    sc_trace(mVcdFile, p_shl2_fu_264_p4, "p_shl2_fu_264_p4");
    sc_trace(mVcdFile, p_shl_fu_253_p3, "p_shl_fu_253_p3");
    sc_trace(mVcdFile, add_ln107_fu_244_p2, "add_ln107_fu_244_p2");
    sc_trace(mVcdFile, add_ln107_1_fu_273_p2, "add_ln107_1_fu_273_p2");
    sc_trace(mVcdFile, trunc_ln107_2_fu_301_p1, "trunc_ln107_2_fu_301_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

FrameProcessing_do_gen::~FrameProcessing_do_gen() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void FrameProcessing_do_gen::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state2;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_186_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln60_fu_192_p2.read()))) {
        i1_0_reg_142 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln60_reg_380.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln70_fu_316_p2.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))))) {
        i1_0_reg_142 = i_3_fu_322_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_186_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_192_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_fu_198_p2.read()))) {
        i3_0_reg_122 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_384.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln124_fu_285_p2.read()) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))))) {
        i3_0_reg_122 = i_4_fu_291_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln51_fu_186_p2.read()))) {
        i_0_reg_153 = ap_const_lv6_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(icmp_ln57_fu_328_p2.read(), ap_const_lv1_0) && 
                !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))))) {
        i_0_reg_153 = i_fu_334_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, rgbv_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, addr_full_n.read())))) {
        v_assign_reg_133 = curr_off_1_reg_414.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_186_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_192_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_198_p2.read()))) {
        v_assign_reg_133 = curr_off_fu_238_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_186_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_192_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_fu_198_p2.read()))) {
        add_ln107_2_reg_393 = add_ln107_2_fu_279_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_reg_384.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_305_p2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))))) {
        curr_off_1_reg_414 = curr_off_1_fu_310_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
        icmp_ln51_reg_376 = icmp_ln51_fu_186_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_186_p2.read()))) {
        icmp_ln60_reg_380 = icmp_ln60_fu_192_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln51_fu_186_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_192_p2.read()))) {
        icmp_ln96_reg_384 = icmp_ln96_fu_198_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
  esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read()) && 
  !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read())))))) {
        reg_164 = e_dout.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
  esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
  esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)))) {
        reg_168 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_reg_384.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))))) {
        v_assign_cast_reg_406 = v_assign_cast_fu_297_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
        val_V_5_reg_351 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
        val_V_6_reg_356 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
        val_V_7_reg_361 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
        val_V_8_reg_369 = e_dout.read();
    }
}

void FrameProcessing_do_gen::thread_add_ln103_fu_232_p2() {
    add_ln103_fu_232_p2 = (!zext_ln103_fu_204_p1.read().is_01() || !zext_ln103_1_fu_216_p1.read().is_01())? sc_lv<26>(): (sc_biguint<26>(zext_ln103_fu_204_p1.read()) + sc_biguint<26>(zext_ln103_1_fu_216_p1.read()));
}

void FrameProcessing_do_gen::thread_add_ln107_1_fu_273_p2() {
    add_ln107_1_fu_273_p2 = (!p_shl2_fu_264_p4.read().is_01() || !p_shl_fu_253_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(p_shl2_fu_264_p4.read()) + sc_biguint<16>(p_shl_fu_253_p3.read()));
}

void FrameProcessing_do_gen::thread_add_ln107_2_fu_279_p2() {
    add_ln107_2_fu_279_p2 = (!add_ln107_fu_244_p2.read().is_01() || !add_ln107_1_fu_273_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln107_fu_244_p2.read()) + sc_biguint<16>(add_ln107_1_fu_273_p2.read()));
}

void FrameProcessing_do_gen::thread_add_ln107_fu_244_p2() {
    add_ln107_fu_244_p2 = (!ap_const_lv16_14.is_01() || !mot1_fu_180_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_14) + sc_biguint<16>(mot1_fu_180_p3.read()));
}

void FrameProcessing_do_gen::thread_addr_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        addr_blk_n = addr_full_n.read();
    } else {
        addr_blk_n = ap_const_logic_1;
    }
}

void FrameProcessing_do_gen::thread_addr_din() {
    addr_din = v_assign_cast_reg_406.read();
}

void FrameProcessing_do_gen::thread_addr_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, rgbv_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, addr_full_n.read())))) {
        addr_write = ap_const_logic_1;
    } else {
        addr_write = ap_const_logic_0;
    }
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void FrameProcessing_do_gen::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void FrameProcessing_do_gen::thread_ap_block_state10() {
    ap_block_state10 = ((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read())));
}

void FrameProcessing_do_gen::thread_ap_block_state12() {
    ap_block_state12 = (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, rgbv_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, addr_full_n.read()));
}

void FrameProcessing_do_gen::thread_ap_predicate_op70_read_state10() {
    ap_predicate_op70_read_state10 = (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_384.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln124_fu_285_p2.read()));
}

void FrameProcessing_do_gen::thread_ap_predicate_op79_read_state10() {
    ap_predicate_op79_read_state10 = (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_reg_384.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_305_p2.read()));
}

void FrameProcessing_do_gen::thread_ap_predicate_op88_read_state10() {
    ap_predicate_op88_read_state10 = (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln60_reg_380.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln70_fu_316_p2.read()));
}

void FrameProcessing_do_gen::thread_ap_predicate_op97_read_state10() {
    ap_predicate_op97_read_state10 = (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_ln57_fu_328_p2.read(), ap_const_lv1_0));
}

void FrameProcessing_do_gen::thread_curr_off_1_fu_310_p2() {
    curr_off_1_fu_310_p2 = (!v_assign_reg_133.read().is_01() || !ap_const_lv26_1.is_01())? sc_lv<26>(): (sc_biguint<26>(v_assign_reg_133.read()) + sc_biguint<26>(ap_const_lv26_1));
}

void FrameProcessing_do_gen::thread_curr_off_fu_238_p2() {
    curr_off_fu_238_p2 = (!zext_ln103_2_fu_228_p1.read().is_01() || !add_ln103_fu_232_p2.read().is_01())? sc_lv<26>(): (sc_biguint<26>(zext_ln103_2_fu_228_p1.read()) + sc_biguint<26>(add_ln103_fu_232_p2.read()));
}

void FrameProcessing_do_gen::thread_e_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(icmp_ln57_fu_328_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln60_reg_380.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln70_fu_316_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_reg_384.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_305_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_384.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln124_fu_285_p2.read())))) {
        e_blk_n = e_empty_n.read();
    } else {
        e_blk_n = ap_const_logic_1;
    }
}

void FrameProcessing_do_gen::thread_e_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, rgbv_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, addr_full_n.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read())))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read())))))) {
        e_read = ap_const_logic_1;
    } else {
        e_read = ap_const_logic_0;
    }
}

void FrameProcessing_do_gen::thread_i_3_fu_322_p2() {
    i_3_fu_322_p2 = (!i1_0_reg_142.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i1_0_reg_142.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void FrameProcessing_do_gen::thread_i_4_fu_291_p2() {
    i_4_fu_291_p2 = (!i3_0_reg_122.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i3_0_reg_122.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void FrameProcessing_do_gen::thread_i_fu_334_p2() {
    i_fu_334_p2 = (!i_0_reg_153.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_0_reg_153.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void FrameProcessing_do_gen::thread_icmp_ln107_fu_305_p2() {
    icmp_ln107_fu_305_p2 = (!trunc_ln107_2_fu_301_p1.read().is_01() || !add_ln107_2_reg_393.read().is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln107_2_fu_301_p1.read() == add_ln107_2_reg_393.read());
}

void FrameProcessing_do_gen::thread_icmp_ln124_fu_285_p2() {
    icmp_ln124_fu_285_p2 = (!i3_0_reg_122.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_122.read() == ap_const_lv7_40);
}

void FrameProcessing_do_gen::thread_icmp_ln51_fu_186_p2() {
    icmp_ln51_fu_186_p2 = (!type_fu_172_p3.read().is_01() || !ap_const_lv16_22.is_01())? sc_lv<1>(): sc_lv<1>(type_fu_172_p3.read() == ap_const_lv16_22);
}

void FrameProcessing_do_gen::thread_icmp_ln57_fu_328_p2() {
    icmp_ln57_fu_328_p2 = (!i_0_reg_153.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_153.read() == ap_const_lv6_3C);
}

void FrameProcessing_do_gen::thread_icmp_ln60_fu_192_p2() {
    icmp_ln60_fu_192_p2 = (!type_fu_172_p3.read().is_01() || !ap_const_lv16_33.is_01())? sc_lv<1>(): sc_lv<1>(type_fu_172_p3.read() == ap_const_lv16_33);
}

void FrameProcessing_do_gen::thread_icmp_ln70_fu_316_p2() {
    icmp_ln70_fu_316_p2 = (!i1_0_reg_142.read().is_01() || !ap_const_lv6_3C.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_142.read() == ap_const_lv6_3C);
}

void FrameProcessing_do_gen::thread_icmp_ln96_fu_198_p2() {
    icmp_ln96_fu_198_p2 = (!type_fu_172_p3.read().is_01() || !ap_const_lv16_11.is_01())? sc_lv<1>(): sc_lv<1>(type_fu_172_p3.read() == ap_const_lv16_11);
}

void FrameProcessing_do_gen::thread_mot1_fu_180_p3() {
    mot1_fu_180_p3 = esl_concat<8,8>(val_V_6_reg_356.read(), val_V_5_reg_351.read());
}

void FrameProcessing_do_gen::thread_p_shl2_fu_264_p4() {
    p_shl2_fu_264_p4 = esl_concat<9,7>(esl_concat<1,8>(trunc_ln107_1_fu_261_p1.read(), val_V_7_reg_361.read()), ap_const_lv7_0);
}

void FrameProcessing_do_gen::thread_p_shl_fu_253_p3() {
    p_shl_fu_253_p3 = esl_concat<7,9>(trunc_ln107_fu_250_p1.read(), ap_const_lv9_0);
}

void FrameProcessing_do_gen::thread_rgbv_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        rgbv_blk_n = rgbv_full_n.read();
    } else {
        rgbv_blk_n = ap_const_logic_1;
    }
}

void FrameProcessing_do_gen::thread_rgbv_din() {
    rgbv_din = esl_concat<16,8>(esl_concat<8,8>(reg_164.read(), reg_168.read()), e_dout.read());
}

void FrameProcessing_do_gen::thread_rgbv_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, rgbv_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, addr_full_n.read())))) {
        rgbv_write = ap_const_logic_1;
    } else {
        rgbv_write = ap_const_logic_0;
    }
}

void FrameProcessing_do_gen::thread_shl_ln103_1_fu_220_p4() {
    shl_ln103_1_fu_220_p4 = esl_concat<16,7>(esl_concat<8,8>(val_V_8_reg_369.read(), val_V_7_reg_361.read()), ap_const_lv7_0);
}

void FrameProcessing_do_gen::thread_shl_ln_fu_208_p4() {
    shl_ln_fu_208_p4 = esl_concat<16,9>(esl_concat<8,8>(val_V_8_reg_369.read(), val_V_7_reg_361.read()), ap_const_lv9_0);
}

void FrameProcessing_do_gen::thread_trunc_ln107_1_fu_261_p1() {
    trunc_ln107_1_fu_261_p1 = val_V_8_reg_369.read().range(1-1, 0);
}

void FrameProcessing_do_gen::thread_trunc_ln107_2_fu_301_p1() {
    trunc_ln107_2_fu_301_p1 = v_assign_reg_133.read().range(16-1, 0);
}

void FrameProcessing_do_gen::thread_trunc_ln107_fu_250_p1() {
    trunc_ln107_fu_250_p1 = val_V_7_reg_361.read().range(7-1, 0);
}

void FrameProcessing_do_gen::thread_type_fu_172_p3() {
    type_fu_172_p3 = esl_concat<8,8>(reg_168.read(), reg_164.read());
}

void FrameProcessing_do_gen::thread_v_assign_cast_fu_297_p1() {
    v_assign_cast_fu_297_p1 = esl_zext<32,26>(v_assign_reg_133.read());
}

void FrameProcessing_do_gen::thread_zext_ln103_1_fu_216_p1() {
    zext_ln103_1_fu_216_p1 = esl_zext<26,25>(shl_ln_fu_208_p4.read());
}

void FrameProcessing_do_gen::thread_zext_ln103_2_fu_228_p1() {
    zext_ln103_2_fu_228_p1 = esl_zext<26,23>(shl_ln103_1_fu_220_p4.read());
}

void FrameProcessing_do_gen::thread_zext_ln103_fu_204_p1() {
    zext_ln103_fu_204_p1 = esl_zext<26,16>(mot1_fu_180_p3.read());
}

void FrameProcessing_do_gen::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))) && ((((esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_1) && 
     esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln57_fu_328_p2.read())) || 
    (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
     esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln60_reg_380.read()) && 
     esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln70_fu_316_p2.read()))) || 
   (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && 
    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_reg_384.read()) && 
    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_305_p2.read()))) || 
  (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_384.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln124_fu_285_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln96_reg_384.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln107_fu_305_p2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && !((esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op70_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op79_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op88_read_state10.read())) || (esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op97_read_state10.read()))) && (((esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_1) && 
    esl_seteq<1,1,1>(icmp_ln57_fu_328_p2.read(), ap_const_lv1_0)) || 
   (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln60_reg_380.read()) && 
    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln70_fu_316_p2.read()))) || 
  (esl_seteq<1,1,1>(icmp_ln51_reg_376.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_380.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln96_reg_384.read()) && 
   esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln124_fu_285_p2.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(e_empty_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, rgbv_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, addr_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXX";
            break;
    }
}

}

