// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Seuil_calc2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Seuil_calc2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Seuil_calc2::ap_const_logic_0 = sc_dt::Log_0;
const bool Seuil_calc2::ap_const_boolean_1 = true;

Seuil_calc2::Seuil_calc2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_Seuil_calc2_do_gen_fu_56 = new Seuil_calc2_do_gen("grp_Seuil_calc2_do_gen_fu_56");
    grp_Seuil_calc2_do_gen_fu_56->ap_clk(clock);
    grp_Seuil_calc2_do_gen_fu_56->ap_rst(reset);
    grp_Seuil_calc2_do_gen_fu_56->e_dout(e_dout);
    grp_Seuil_calc2_do_gen_fu_56->e_empty_n(e_empty_n);
    grp_Seuil_calc2_do_gen_fu_56->e_read(grp_Seuil_calc2_do_gen_fu_56_e_read);
    grp_Seuil_calc2_do_gen_fu_56->detect_din(grp_Seuil_calc2_do_gen_fu_56_detect_din);
    grp_Seuil_calc2_do_gen_fu_56->detect_full_n(detect_full_n);
    grp_Seuil_calc2_do_gen_fu_56->detect_write(grp_Seuil_calc2_do_gen_fu_56_detect_write);

    SC_METHOD(thread_detect_din);
    sensitive << ( grp_Seuil_calc2_do_gen_fu_56_detect_din );
    sensitive << ( grp_Seuil_calc2_do_gen_fu_56_detect_write );

    SC_METHOD(thread_detect_write);
    sensitive << ( grp_Seuil_calc2_do_gen_fu_56_detect_write );

    SC_METHOD(thread_e_read);
    sensitive << ( grp_Seuil_calc2_do_gen_fu_56_e_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Seuil_calc2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, clock, "(port)clock");
    sc_trace(mVcdFile, reset, "(port)reset");
    sc_trace(mVcdFile, e_dout, "(port)e_dout");
    sc_trace(mVcdFile, e_empty_n, "(port)e_empty_n");
    sc_trace(mVcdFile, e_read, "(port)e_read");
    sc_trace(mVcdFile, detect_din, "(port)detect_din");
    sc_trace(mVcdFile, detect_full_n, "(port)detect_full_n");
    sc_trace(mVcdFile, detect_write, "(port)detect_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, grp_Seuil_calc2_do_gen_fu_56_e_read, "grp_Seuil_calc2_do_gen_fu_56_e_read");
    sc_trace(mVcdFile, grp_Seuil_calc2_do_gen_fu_56_detect_din, "grp_Seuil_calc2_do_gen_fu_56_detect_din");
    sc_trace(mVcdFile, grp_Seuil_calc2_do_gen_fu_56_detect_write, "grp_Seuil_calc2_do_gen_fu_56_detect_write");
#endif

    }
}

Seuil_calc2::~Seuil_calc2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_Seuil_calc2_do_gen_fu_56;
}

void Seuil_calc2::thread_detect_din() {
    detect_din = grp_Seuil_calc2_do_gen_fu_56_detect_din.read();
}

void Seuil_calc2::thread_detect_write() {
    detect_write = grp_Seuil_calc2_do_gen_fu_56_detect_write.read();
}

void Seuil_calc2::thread_e_read() {
    e_read = grp_Seuil_calc2_do_gen_fu_56_e_read.read();
}

}

