// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Seuil_calc2_do_gen_HH_
#define _Seuil_calc2_do_gen_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Seuil_calc2_mac_mdEe.h"
#include "Seuil_calc2_mul_meOg.h"
#include "Seuil_calc2_mul_mfYi.h"

namespace ap_rtl {

struct Seuil_calc2_do_gen : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<8> > e_dout;
    sc_in< sc_logic > e_empty_n;
    sc_out< sc_logic > e_read;
    sc_out< sc_logic > detect_din;
    sc_in< sc_logic > detect_full_n;
    sc_out< sc_logic > detect_write;


    // Module declarations
    Seuil_calc2_do_gen(sc_module_name name);
    SC_HAS_PROCESS(Seuil_calc2_do_gen);

    ~Seuil_calc2_do_gen();

    sc_trace_file* mVcdFile;

    Seuil_calc2_mac_mdEe<1,1,8,8,16,17>* Seuil_calc2_mac_mdEe_U22;
    Seuil_calc2_mul_meOg<1,1,11,11,22>* Seuil_calc2_mul_meOg_U23;
    Seuil_calc2_mul_mfYi<1,1,17,6,27>* Seuil_calc2_mul_mfYi_U24;
    sc_signal< sc_logic > e_blk_n;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > detect_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_lv<22> > p_0108_0_reg_221;
    sc_signal< sc_lv<8> > val_V_reg_876;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter4;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<8> > val_V_reg_876_pp0_iter1_reg;
    sc_signal< sc_lv<17> > grp_fu_664_p3;
    sc_signal< sc_lv<17> > ret_V_reg_882;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<11> > ps_V_fu_437_p2;
    sc_signal< sc_lv<11> > ps_V_reg_887;
    sc_signal< sc_lv<22> > sum_V_fu_454_p2;
    sc_signal< sc_lv<22> > sum_V_reg_892;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<17> > res_2_V_fu_476_p3;
    sc_signal< sc_lv<17> > res_2_V_reg_897;
    sc_signal< sc_lv<22> > ret_V_6_fu_672_p2;
    sc_signal< sc_lv<22> > ret_V_6_reg_902;
    sc_signal< sc_lv<27> > mul_ln895_fu_678_p2;
    sc_signal< sc_lv<27> > mul_ln895_reg_907;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_lv<22> > ap_phi_mux_p_0108_0_phi_fu_225_p4;
    sc_signal< sc_lv<8> > p_0343_0_fu_80;
    sc_signal< sc_lv<8> > ap_sig_allocacmp_p_0343_0_load;
    sc_signal< sc_lv<8> > x0_V_fu_84;
    sc_signal< sc_lv<8> > buffer_1_V_fu_88;
    sc_signal< sc_lv<8> > buffer_2_V_fu_92;
    sc_signal< sc_lv<8> > buffer_3_V_fu_96;
    sc_signal< sc_lv<8> > buffer_4_V_fu_100;
    sc_signal< sc_lv<8> > buffer_5_V_fu_104;
    sc_signal< sc_lv<8> > buffer_6_V_fu_108;
    sc_signal< sc_lv<8> > buffer_7_V_fu_112;
    sc_signal< sc_lv<8> > buffer_8_V_fu_116;
    sc_signal< sc_lv<8> > buffer_9_V_fu_120;
    sc_signal< sc_lv<8> > buffer_10_V_fu_124;
    sc_signal< sc_lv<8> > buffer_11_V_fu_128;
    sc_signal< sc_lv<8> > buffer_12_V_fu_132;
    sc_signal< sc_lv<8> > buffer_13_V_fu_136;
    sc_signal< sc_lv<8> > buffer_14_V_fu_140;
    sc_signal< sc_lv<8> > buffer_15_V_fu_144;
    sc_signal< sc_lv<8> > buffer_16_V_fu_148;
    sc_signal< sc_lv<8> > buffer_17_V_fu_152;
    sc_signal< sc_lv<8> > buffer_18_V_fu_156;
    sc_signal< sc_lv<8> > buffer_19_V_fu_160;
    sc_signal< sc_lv<8> > buffer_20_V_fu_164;
    sc_signal< sc_lv<8> > buffer_21_V_fu_168;
    sc_signal< sc_lv<8> > buffer_22_V_fu_172;
    sc_signal< sc_lv<8> > buffer_23_V_fu_176;
    sc_signal< sc_lv<8> > buffer_24_V_fu_180;
    sc_signal< sc_lv<8> > buffer_25_V_fu_184;
    sc_signal< sc_lv<8> > buffer_26_V_fu_188;
    sc_signal< sc_lv<8> > buffer_27_V_fu_192;
    sc_signal< sc_lv<8> > buffer_28_V_fu_196;
    sc_signal< sc_lv<8> > buffer_29_V_fu_200;
    sc_signal< sc_lv<8> > buffer_30_V_fu_204;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_lv<8> > ret_V_5_fu_242_p0;
    sc_signal< sc_lv<16> > lhs_V_5_fu_239_p1;
    sc_signal< sc_lv<8> > ret_V_5_fu_242_p1;
    sc_signal< sc_lv<16> > ret_V_5_fu_242_p2;
    sc_signal< sc_lv<9> > zext_ln215_fu_345_p1;
    sc_signal< sc_lv<9> > zext_ln215_1_fu_349_p1;
    sc_signal< sc_lv<9> > add_ln215_fu_377_p2;
    sc_signal< sc_lv<9> > zext_ln215_3_fu_357_p1;
    sc_signal< sc_lv<9> > zext_ln215_2_fu_353_p1;
    sc_signal< sc_lv<9> > add_ln215_1_fu_387_p2;
    sc_signal< sc_lv<10> > zext_ln215_8_fu_383_p1;
    sc_signal< sc_lv<10> > zext_ln215_9_fu_393_p1;
    sc_signal< sc_lv<10> > add_ln215_2_fu_397_p2;
    sc_signal< sc_lv<9> > zext_ln215_5_fu_365_p1;
    sc_signal< sc_lv<9> > zext_ln215_4_fu_361_p1;
    sc_signal< sc_lv<9> > add_ln215_3_fu_407_p2;
    sc_signal< sc_lv<9> > zext_ln215_7_fu_373_p1;
    sc_signal< sc_lv<9> > zext_ln215_6_fu_369_p1;
    sc_signal< sc_lv<9> > add_ln215_4_fu_417_p2;
    sc_signal< sc_lv<10> > zext_ln215_11_fu_413_p1;
    sc_signal< sc_lv<10> > zext_ln215_12_fu_423_p1;
    sc_signal< sc_lv<10> > add_ln215_5_fu_427_p2;
    sc_signal< sc_lv<11> > zext_ln215_10_fu_403_p1;
    sc_signal< sc_lv<11> > zext_ln215_13_fu_433_p1;
    sc_signal< sc_lv<20> > shl_ln_fu_443_p3;
    sc_signal< sc_lv<22> > sext_ln700_fu_450_p1;
    sc_signal< sc_lv<17> > trunc_ln_fu_460_p4;
    sc_signal< sc_lv<1> > icmp_ln879_fu_470_p2;
    sc_signal< sc_lv<27> > zext_ln895_1_fu_649_p1;
    sc_signal< sc_lv<1> > icmp_ln895_fu_652_p2;
    sc_signal< sc_lv<8> > grp_fu_664_p0;
    sc_signal< sc_lv<16> > lhs_V_4_fu_235_p1;
    sc_signal< sc_lv<8> > grp_fu_664_p1;
    sc_signal< sc_lv<16> > grp_fu_664_p2;
    sc_signal< sc_lv<11> > ret_V_6_fu_672_p0;
    sc_signal< sc_lv<22> > lhs_V_6_fu_643_p1;
    sc_signal< sc_lv<11> > ret_V_6_fu_672_p1;
    sc_signal< sc_lv<17> > mul_ln895_fu_678_p0;
    sc_signal< sc_lv<6> > mul_ln895_fu_678_p1;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_lv<17> > grp_fu_664_p20;
    sc_signal< sc_lv<27> > mul_ln895_fu_678_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_pp0_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<22> ap_const_lv22_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<17> ap_const_lv17_0;
    static const sc_lv<17> ap_const_lv17_1F;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<27> ap_const_lv27_1B;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln215_1_fu_387_p2();
    void thread_add_ln215_2_fu_397_p2();
    void thread_add_ln215_3_fu_407_p2();
    void thread_add_ln215_4_fu_417_p2();
    void thread_add_ln215_5_fu_427_p2();
    void thread_add_ln215_fu_377_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_block_state5_pp0_stage0_iter3();
    void thread_ap_block_state6_pp0_stage0_iter4();
    void thread_ap_enable_pp0();
    void thread_ap_idle_pp0();
    void thread_ap_phi_mux_p_0108_0_phi_fu_225_p4();
    void thread_ap_sig_allocacmp_p_0343_0_load();
    void thread_detect_blk_n();
    void thread_detect_din();
    void thread_detect_write();
    void thread_e_blk_n();
    void thread_e_read();
    void thread_grp_fu_664_p0();
    void thread_grp_fu_664_p1();
    void thread_grp_fu_664_p2();
    void thread_grp_fu_664_p20();
    void thread_icmp_ln879_fu_470_p2();
    void thread_icmp_ln895_fu_652_p2();
    void thread_lhs_V_4_fu_235_p1();
    void thread_lhs_V_5_fu_239_p1();
    void thread_lhs_V_6_fu_643_p1();
    void thread_mul_ln895_fu_678_p0();
    void thread_mul_ln895_fu_678_p00();
    void thread_mul_ln895_fu_678_p1();
    void thread_ps_V_fu_437_p2();
    void thread_res_2_V_fu_476_p3();
    void thread_ret_V_5_fu_242_p0();
    void thread_ret_V_5_fu_242_p1();
    void thread_ret_V_5_fu_242_p2();
    void thread_ret_V_6_fu_672_p0();
    void thread_ret_V_6_fu_672_p1();
    void thread_sext_ln700_fu_450_p1();
    void thread_shl_ln_fu_443_p3();
    void thread_sum_V_fu_454_p2();
    void thread_trunc_ln_fu_460_p4();
    void thread_zext_ln215_10_fu_403_p1();
    void thread_zext_ln215_11_fu_413_p1();
    void thread_zext_ln215_12_fu_423_p1();
    void thread_zext_ln215_13_fu_433_p1();
    void thread_zext_ln215_1_fu_349_p1();
    void thread_zext_ln215_2_fu_353_p1();
    void thread_zext_ln215_3_fu_357_p1();
    void thread_zext_ln215_4_fu_361_p1();
    void thread_zext_ln215_5_fu_365_p1();
    void thread_zext_ln215_6_fu_369_p1();
    void thread_zext_ln215_7_fu_373_p1();
    void thread_zext_ln215_8_fu_383_p1();
    void thread_zext_ln215_9_fu_393_p1();
    void thread_zext_ln215_fu_345_p1();
    void thread_zext_ln895_1_fu_649_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
