// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CRCCheck_do_gen.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CRCCheck_do_gen::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CRCCheck_do_gen::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_state1 = "1";
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_state2 = "10";
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_state6 = "1000";
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_state7 = "10000";
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_state8 = "100000";
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_pp1_stage0 = "1000000";
const sc_lv<8> CRCCheck_do_gen::ap_ST_fsm_state11 = "10000000";
const bool CRCCheck_do_gen::ap_const_boolean_1 = true;
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_2 = "10";
const bool CRCCheck_do_gen::ap_const_boolean_0 = false;
const sc_lv<1> CRCCheck_do_gen::ap_const_lv1_0 = "0";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_4 = "100";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_6 = "110";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_5 = "101";
const sc_lv<1> CRCCheck_do_gen::ap_const_lv1_1 = "1";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_1 = "1";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<7> CRCCheck_do_gen::ap_const_lv7_0 = "0000000";
const sc_lv<3> CRCCheck_do_gen::ap_const_lv3_0 = "000";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_3 = "11";
const sc_lv<2> CRCCheck_do_gen::ap_const_lv2_0 = "00";
const sc_lv<2> CRCCheck_do_gen::ap_const_lv2_1 = "1";
const sc_lv<2> CRCCheck_do_gen::ap_const_lv2_2 = "10";
const sc_lv<2> CRCCheck_do_gen::ap_const_lv2_3 = "11";
const sc_lv<7> CRCCheck_do_gen::ap_const_lv7_44 = "1000100";
const sc_lv<7> CRCCheck_do_gen::ap_const_lv7_1 = "1";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_1F = "11111";
const sc_lv<32> CRCCheck_do_gen::ap_const_lv32_82F63B78 = "10000010111101100011101101111000";
const sc_lv<3> CRCCheck_do_gen::ap_const_lv3_4 = "100";
const sc_lv<3> CRCCheck_do_gen::ap_const_lv3_1 = "1";

CRCCheck_do_gen::CRCCheck_do_gen(sc_module_name name) : sc_module(name), mVcdFile(0) {
    ibuffer_V_U = new CRCCheck_do_gen_ibkb("ibuffer_V_U");
    ibuffer_V_U->clk(ap_clk);
    ibuffer_V_U->reset(ap_rst);
    ibuffer_V_U->address0(ibuffer_V_address0);
    ibuffer_V_U->ce0(ibuffer_V_ce0);
    ibuffer_V_U->we0(ibuffer_V_we0);
    ibuffer_V_U->d0(e_dout);
    ibuffer_V_U->q0(ibuffer_V_q0);
    CRCCheck_mux_42_8cud_U9 = new CRCCheck_mux_42_8cud<1,1,8,8,8,8,2,8>("CRCCheck_mux_42_8cud_U9");
    CRCCheck_mux_42_8cud_U9->din0(crc_t_3_fu_102);
    CRCCheck_mux_42_8cud_U9->din1(crc_t_3_1_fu_106);
    CRCCheck_mux_42_8cud_U9->din2(crc_t_3_2_fu_110);
    CRCCheck_mux_42_8cud_U9->din3(crc_t_3_3_fu_114);
    CRCCheck_mux_42_8cud_U9->din4(tmp_11_fu_585_p5);
    CRCCheck_mux_42_8cud_U9->dout(tmp_11_fu_585_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_R_fu_253_p2);
    sensitive << ( ap_phi_mux_R_0_phi_fu_160_p4 );
    sensitive << ( zext_ln46_fu_241_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( e_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln41_reg_658 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( e_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln41_reg_658 );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);
    sensitive << ( s_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln68_reg_711 );

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( s_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln68_reg_711 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( s_full_n );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln68_reg_711 );

    SC_METHOD(thread_ap_block_state10_pp1_stage0_iter1);
    sensitive << ( s_full_n );
    sensitive << ( icmp_ln68_reg_711 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( e_empty_n );
    sensitive << ( icmp_ln41_reg_658 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state7);
    sensitive << ( e_empty_n );
    sensitive << ( icmp_ln54_fu_515_p2 );

    SC_METHOD(thread_ap_block_state9_pp1_stage0_iter0);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln41_fu_224_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state9);
    sensitive << ( icmp_ln68_fu_617_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_phi_mux_R_0_phi_fu_160_p4);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( R_0_reg_156 );
    sensitive << ( icmp_ln41_reg_658_pp0_iter1_reg );
    sensitive << ( select_ln49_7_fu_507_p3 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_172_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln41_reg_658 );
    sensitive << ( i_0_reg_168 );
    sensitive << ( i_5_reg_662 );

    SC_METHOD(thread_crc_fu_603_p3);
    sensitive << ( trunc_ln59_1_fu_599_p1 );
    sensitive << ( tmp_11_fu_585_p6 );

    SC_METHOD(thread_e_blk_n);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln41_reg_658 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln54_fu_515_p2 );

    SC_METHOD(thread_e_read);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln41_reg_658 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln54_fu_515_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_5_fu_230_p2);
    sensitive << ( ap_phi_mux_i_0_phi_fu_172_p4 );

    SC_METHOD(thread_i_6_fu_557_p2);
    sensitive << ( i2_0_reg_202 );

    SC_METHOD(thread_i_7_fu_623_p2);
    sensitive << ( i3_0_reg_213 );

    SC_METHOD(thread_i_fu_521_p2);
    sensitive << ( i1_0_reg_180 );

    SC_METHOD(thread_ibuffer_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( zext_ln45_fu_236_p1 );
    sensitive << ( zext_ln70_fu_629_p1 );

    SC_METHOD(thread_ibuffer_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ibuffer_V_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln41_reg_658 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln41_fu_224_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_172_p4 );

    SC_METHOD(thread_icmp_ln54_fu_515_p2);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln54_fu_515_p2 );
    sensitive << ( i1_0_reg_180 );

    SC_METHOD(thread_icmp_ln58_fu_551_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i2_0_reg_202 );

    SC_METHOD(thread_icmp_ln63_fu_611_p2);
    sensitive << ( R_0_reg_156 );
    sensitive << ( icmp_ln58_fu_551_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( crc_0_reg_191 );

    SC_METHOD(thread_icmp_ln68_fu_617_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( i3_0_reg_213 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_lshr_ln49_1_fu_297_p4);
    sensitive << ( select_ln49_fu_285_p3 );

    SC_METHOD(thread_lshr_ln49_2_fu_329_p4);
    sensitive << ( select_ln49_1_fu_317_p3 );

    SC_METHOD(thread_lshr_ln49_4_fu_391_p4);
    sensitive << ( select_ln49_3_fu_379_p3 );

    SC_METHOD(thread_lshr_ln49_5_fu_423_p4);
    sensitive << ( select_ln49_4_fu_411_p3 );

    SC_METHOD(thread_lshr_ln49_6_fu_455_p4);
    sensitive << ( select_ln49_5_fu_443_p3 );

    SC_METHOD(thread_lshr_ln49_7_fu_487_p4);
    sensitive << ( select_ln49_6_fu_475_p3 );

    SC_METHOD(thread_lshr_ln_fu_265_p4);
    sensitive << ( R_fu_253_p2 );

    SC_METHOD(thread_s_blk_n);
    sensitive << ( s_full_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln68_reg_711 );

    SC_METHOD(thread_s_din);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln68_reg_711 );
    sensitive << ( ibuffer_V_q0 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_s_write);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln68_reg_711 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_select_ln49_1_fu_317_p3);
    sensitive << ( zext_ln49_1_fu_307_p1 );
    sensitive << ( trunc_ln49_fu_293_p1 );
    sensitive << ( xor_ln49_1_fu_311_p2 );

    SC_METHOD(thread_select_ln49_2_fu_349_p3);
    sensitive << ( zext_ln49_2_fu_339_p1 );
    sensitive << ( trunc_ln49_1_fu_325_p1 );
    sensitive << ( xor_ln49_2_fu_343_p2 );

    SC_METHOD(thread_select_ln49_3_fu_379_p3);
    sensitive << ( zext_ln49_3_fu_370_p1 );
    sensitive << ( trunc_ln49_2_fu_367_p1 );
    sensitive << ( xor_ln49_3_fu_373_p2 );

    SC_METHOD(thread_select_ln49_4_fu_411_p3);
    sensitive << ( zext_ln49_4_fu_401_p1 );
    sensitive << ( trunc_ln49_3_fu_387_p1 );
    sensitive << ( xor_ln49_4_fu_405_p2 );

    SC_METHOD(thread_select_ln49_5_fu_443_p3);
    sensitive << ( zext_ln49_5_fu_433_p1 );
    sensitive << ( trunc_ln49_4_fu_419_p1 );
    sensitive << ( xor_ln49_5_fu_437_p2 );

    SC_METHOD(thread_select_ln49_6_fu_475_p3);
    sensitive << ( zext_ln49_6_fu_465_p1 );
    sensitive << ( trunc_ln49_5_fu_451_p1 );
    sensitive << ( xor_ln49_6_fu_469_p2 );

    SC_METHOD(thread_select_ln49_7_fu_507_p3);
    sensitive << ( zext_ln49_7_fu_497_p1 );
    sensitive << ( trunc_ln49_6_fu_483_p1 );
    sensitive << ( xor_ln49_7_fu_501_p2 );

    SC_METHOD(thread_select_ln49_fu_285_p3);
    sensitive << ( zext_ln49_fu_275_p1 );
    sensitive << ( xor_ln46_1_fu_259_p2 );
    sensitive << ( xor_ln49_fu_279_p2 );

    SC_METHOD(thread_tmp_11_fu_585_p5);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( trunc_ln59_fu_575_p1 );

    SC_METHOD(thread_trunc_ln46_1_fu_249_p1);
    sensitive << ( ap_phi_mux_R_0_phi_fu_160_p4 );

    SC_METHOD(thread_trunc_ln46_fu_245_p1);
    sensitive << ( e_dout );

    SC_METHOD(thread_trunc_ln49_1_fu_325_p1);
    sensitive << ( select_ln49_1_fu_317_p3 );

    SC_METHOD(thread_trunc_ln49_2_fu_367_p1);
    sensitive << ( select_ln49_2_reg_667 );

    SC_METHOD(thread_trunc_ln49_3_fu_387_p1);
    sensitive << ( select_ln49_3_fu_379_p3 );

    SC_METHOD(thread_trunc_ln49_4_fu_419_p1);
    sensitive << ( select_ln49_4_fu_411_p3 );

    SC_METHOD(thread_trunc_ln49_5_fu_451_p1);
    sensitive << ( select_ln49_5_fu_443_p3 );

    SC_METHOD(thread_trunc_ln49_6_fu_483_p1);
    sensitive << ( select_ln49_6_fu_475_p3 );

    SC_METHOD(thread_trunc_ln49_fu_293_p1);
    sensitive << ( select_ln49_fu_285_p3 );

    SC_METHOD(thread_trunc_ln55_fu_527_p1);
    sensitive << ( i1_0_reg_180 );

    SC_METHOD(thread_trunc_ln59_1_fu_599_p1);
    sensitive << ( crc_0_reg_191 );

    SC_METHOD(thread_trunc_ln59_fu_575_p1);
    sensitive << ( i2_0_reg_202 );

    SC_METHOD(thread_xor_ln46_1_fu_259_p2);
    sensitive << ( trunc_ln46_1_fu_249_p1 );
    sensitive << ( trunc_ln46_fu_245_p1 );

    SC_METHOD(thread_xor_ln49_1_fu_311_p2);
    sensitive << ( zext_ln49_1_fu_307_p1 );

    SC_METHOD(thread_xor_ln49_2_fu_343_p2);
    sensitive << ( zext_ln49_2_fu_339_p1 );

    SC_METHOD(thread_xor_ln49_3_fu_373_p2);
    sensitive << ( zext_ln49_3_fu_370_p1 );

    SC_METHOD(thread_xor_ln49_4_fu_405_p2);
    sensitive << ( zext_ln49_4_fu_401_p1 );

    SC_METHOD(thread_xor_ln49_5_fu_437_p2);
    sensitive << ( zext_ln49_5_fu_433_p1 );

    SC_METHOD(thread_xor_ln49_6_fu_469_p2);
    sensitive << ( zext_ln49_6_fu_465_p1 );

    SC_METHOD(thread_xor_ln49_7_fu_501_p2);
    sensitive << ( zext_ln49_7_fu_497_p1 );

    SC_METHOD(thread_xor_ln49_fu_279_p2);
    sensitive << ( zext_ln49_fu_275_p1 );

    SC_METHOD(thread_zext_ln45_fu_236_p1);
    sensitive << ( i_0_reg_168 );

    SC_METHOD(thread_zext_ln46_fu_241_p1);
    sensitive << ( e_dout );

    SC_METHOD(thread_zext_ln49_1_fu_307_p1);
    sensitive << ( lshr_ln49_1_fu_297_p4 );

    SC_METHOD(thread_zext_ln49_2_fu_339_p1);
    sensitive << ( lshr_ln49_2_fu_329_p4 );

    SC_METHOD(thread_zext_ln49_3_fu_370_p1);
    sensitive << ( lshr_ln49_3_reg_672 );

    SC_METHOD(thread_zext_ln49_4_fu_401_p1);
    sensitive << ( lshr_ln49_4_fu_391_p4 );

    SC_METHOD(thread_zext_ln49_5_fu_433_p1);
    sensitive << ( lshr_ln49_5_fu_423_p4 );

    SC_METHOD(thread_zext_ln49_6_fu_465_p1);
    sensitive << ( lshr_ln49_6_fu_455_p4 );

    SC_METHOD(thread_zext_ln49_7_fu_497_p1);
    sensitive << ( lshr_ln49_7_fu_487_p4 );

    SC_METHOD(thread_zext_ln49_fu_275_p1);
    sensitive << ( lshr_ln_fu_265_p4 );

    SC_METHOD(thread_zext_ln70_fu_629_p1);
    sensitive << ( i3_0_reg_213 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( e_empty_n );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln54_fu_515_p2 );
    sensitive << ( icmp_ln41_fu_224_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln58_fu_551_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln63_fu_611_p2 );
    sensitive << ( icmp_ln68_fu_617_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );

    ap_CS_fsm = "00000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CRCCheck_do_gen_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, e_dout, "(port)e_dout");
    sc_trace(mVcdFile, e_empty_n, "(port)e_empty_n");
    sc_trace(mVcdFile, e_read, "(port)e_read");
    sc_trace(mVcdFile, s_din, "(port)s_din");
    sc_trace(mVcdFile, s_full_n, "(port)s_full_n");
    sc_trace(mVcdFile, s_write, "(port)s_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, e_blk_n, "e_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln41_reg_658, "icmp_ln41_reg_658");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln54_fu_515_p2, "icmp_ln54_fu_515_p2");
    sc_trace(mVcdFile, s_blk_n, "s_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, icmp_ln68_reg_711, "icmp_ln68_reg_711");
    sc_trace(mVcdFile, R_0_reg_156, "R_0_reg_156");
    sc_trace(mVcdFile, i_0_reg_168, "i_0_reg_168");
    sc_trace(mVcdFile, i3_0_reg_213, "i3_0_reg_213");
    sc_trace(mVcdFile, icmp_ln41_fu_224_p2, "icmp_ln41_fu_224_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln41_reg_658_pp0_iter1_reg, "icmp_ln41_reg_658_pp0_iter1_reg");
    sc_trace(mVcdFile, i_5_fu_230_p2, "i_5_fu_230_p2");
    sc_trace(mVcdFile, i_5_reg_662, "i_5_reg_662");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, select_ln49_2_fu_349_p3, "select_ln49_2_fu_349_p3");
    sc_trace(mVcdFile, select_ln49_2_reg_667, "select_ln49_2_reg_667");
    sc_trace(mVcdFile, lshr_ln49_3_reg_672, "lshr_ln49_3_reg_672");
    sc_trace(mVcdFile, select_ln49_7_fu_507_p3, "select_ln49_7_fu_507_p3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, i_fu_521_p2, "i_fu_521_p2");
    sc_trace(mVcdFile, ap_block_state7, "ap_block_state7");
    sc_trace(mVcdFile, icmp_ln58_fu_551_p2, "icmp_ln58_fu_551_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i_6_fu_557_p2, "i_6_fu_557_p2");
    sc_trace(mVcdFile, crc_fu_603_p3, "crc_fu_603_p3");
    sc_trace(mVcdFile, icmp_ln63_fu_611_p2, "icmp_ln63_fu_611_p2");
    sc_trace(mVcdFile, icmp_ln68_fu_617_p2, "icmp_ln68_fu_617_p2");
    sc_trace(mVcdFile, ap_block_state9_pp1_stage0_iter0, "ap_block_state9_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp1_stage0_iter1, "ap_block_state10_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, i_7_fu_623_p2, "i_7_fu_623_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state9, "ap_condition_pp1_exit_iter0_state9");
    sc_trace(mVcdFile, ibuffer_V_address0, "ibuffer_V_address0");
    sc_trace(mVcdFile, ibuffer_V_ce0, "ibuffer_V_ce0");
    sc_trace(mVcdFile, ibuffer_V_we0, "ibuffer_V_we0");
    sc_trace(mVcdFile, ibuffer_V_q0, "ibuffer_V_q0");
    sc_trace(mVcdFile, ap_phi_mux_R_0_phi_fu_160_p4, "ap_phi_mux_R_0_phi_fu_160_p4");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_172_p4, "ap_phi_mux_i_0_phi_fu_172_p4");
    sc_trace(mVcdFile, i1_0_reg_180, "i1_0_reg_180");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, crc_0_reg_191, "crc_0_reg_191");
    sc_trace(mVcdFile, i2_0_reg_202, "i2_0_reg_202");
    sc_trace(mVcdFile, zext_ln45_fu_236_p1, "zext_ln45_fu_236_p1");
    sc_trace(mVcdFile, zext_ln70_fu_629_p1, "zext_ln70_fu_629_p1");
    sc_trace(mVcdFile, crc_t_3_fu_102, "crc_t_3_fu_102");
    sc_trace(mVcdFile, trunc_ln55_fu_527_p1, "trunc_ln55_fu_527_p1");
    sc_trace(mVcdFile, crc_t_3_1_fu_106, "crc_t_3_1_fu_106");
    sc_trace(mVcdFile, crc_t_3_2_fu_110, "crc_t_3_2_fu_110");
    sc_trace(mVcdFile, crc_t_3_3_fu_114, "crc_t_3_3_fu_114");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, zext_ln46_fu_241_p1, "zext_ln46_fu_241_p1");
    sc_trace(mVcdFile, trunc_ln46_1_fu_249_p1, "trunc_ln46_1_fu_249_p1");
    sc_trace(mVcdFile, trunc_ln46_fu_245_p1, "trunc_ln46_fu_245_p1");
    sc_trace(mVcdFile, R_fu_253_p2, "R_fu_253_p2");
    sc_trace(mVcdFile, lshr_ln_fu_265_p4, "lshr_ln_fu_265_p4");
    sc_trace(mVcdFile, zext_ln49_fu_275_p1, "zext_ln49_fu_275_p1");
    sc_trace(mVcdFile, xor_ln46_1_fu_259_p2, "xor_ln46_1_fu_259_p2");
    sc_trace(mVcdFile, xor_ln49_fu_279_p2, "xor_ln49_fu_279_p2");
    sc_trace(mVcdFile, select_ln49_fu_285_p3, "select_ln49_fu_285_p3");
    sc_trace(mVcdFile, lshr_ln49_1_fu_297_p4, "lshr_ln49_1_fu_297_p4");
    sc_trace(mVcdFile, zext_ln49_1_fu_307_p1, "zext_ln49_1_fu_307_p1");
    sc_trace(mVcdFile, trunc_ln49_fu_293_p1, "trunc_ln49_fu_293_p1");
    sc_trace(mVcdFile, xor_ln49_1_fu_311_p2, "xor_ln49_1_fu_311_p2");
    sc_trace(mVcdFile, select_ln49_1_fu_317_p3, "select_ln49_1_fu_317_p3");
    sc_trace(mVcdFile, lshr_ln49_2_fu_329_p4, "lshr_ln49_2_fu_329_p4");
    sc_trace(mVcdFile, zext_ln49_2_fu_339_p1, "zext_ln49_2_fu_339_p1");
    sc_trace(mVcdFile, trunc_ln49_1_fu_325_p1, "trunc_ln49_1_fu_325_p1");
    sc_trace(mVcdFile, xor_ln49_2_fu_343_p2, "xor_ln49_2_fu_343_p2");
    sc_trace(mVcdFile, zext_ln49_3_fu_370_p1, "zext_ln49_3_fu_370_p1");
    sc_trace(mVcdFile, trunc_ln49_2_fu_367_p1, "trunc_ln49_2_fu_367_p1");
    sc_trace(mVcdFile, xor_ln49_3_fu_373_p2, "xor_ln49_3_fu_373_p2");
    sc_trace(mVcdFile, select_ln49_3_fu_379_p3, "select_ln49_3_fu_379_p3");
    sc_trace(mVcdFile, lshr_ln49_4_fu_391_p4, "lshr_ln49_4_fu_391_p4");
    sc_trace(mVcdFile, zext_ln49_4_fu_401_p1, "zext_ln49_4_fu_401_p1");
    sc_trace(mVcdFile, trunc_ln49_3_fu_387_p1, "trunc_ln49_3_fu_387_p1");
    sc_trace(mVcdFile, xor_ln49_4_fu_405_p2, "xor_ln49_4_fu_405_p2");
    sc_trace(mVcdFile, select_ln49_4_fu_411_p3, "select_ln49_4_fu_411_p3");
    sc_trace(mVcdFile, lshr_ln49_5_fu_423_p4, "lshr_ln49_5_fu_423_p4");
    sc_trace(mVcdFile, zext_ln49_5_fu_433_p1, "zext_ln49_5_fu_433_p1");
    sc_trace(mVcdFile, trunc_ln49_4_fu_419_p1, "trunc_ln49_4_fu_419_p1");
    sc_trace(mVcdFile, xor_ln49_5_fu_437_p2, "xor_ln49_5_fu_437_p2");
    sc_trace(mVcdFile, select_ln49_5_fu_443_p3, "select_ln49_5_fu_443_p3");
    sc_trace(mVcdFile, lshr_ln49_6_fu_455_p4, "lshr_ln49_6_fu_455_p4");
    sc_trace(mVcdFile, zext_ln49_6_fu_465_p1, "zext_ln49_6_fu_465_p1");
    sc_trace(mVcdFile, trunc_ln49_5_fu_451_p1, "trunc_ln49_5_fu_451_p1");
    sc_trace(mVcdFile, xor_ln49_6_fu_469_p2, "xor_ln49_6_fu_469_p2");
    sc_trace(mVcdFile, select_ln49_6_fu_475_p3, "select_ln49_6_fu_475_p3");
    sc_trace(mVcdFile, lshr_ln49_7_fu_487_p4, "lshr_ln49_7_fu_487_p4");
    sc_trace(mVcdFile, zext_ln49_7_fu_497_p1, "zext_ln49_7_fu_497_p1");
    sc_trace(mVcdFile, trunc_ln49_6_fu_483_p1, "trunc_ln49_6_fu_483_p1");
    sc_trace(mVcdFile, xor_ln49_7_fu_501_p2, "xor_ln49_7_fu_501_p2");
    sc_trace(mVcdFile, trunc_ln59_fu_575_p1, "trunc_ln59_fu_575_p1");
    sc_trace(mVcdFile, tmp_11_fu_585_p5, "tmp_11_fu_585_p5");
    sc_trace(mVcdFile, trunc_ln59_1_fu_599_p1, "trunc_ln59_1_fu_599_p1");
    sc_trace(mVcdFile, tmp_11_fu_585_p6, "tmp_11_fu_585_p6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
}

CRCCheck_do_gen::~CRCCheck_do_gen() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete ibuffer_V_U;
    delete CRCCheck_mux_42_8cud_U9;
}

void CRCCheck_do_gen::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_reg_658_pp0_iter1_reg.read()))) {
        R_0_reg_156 = select_ln49_7_fu_507_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        R_0_reg_156 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state9.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                    esl_seteq<1,1,1>(icmp_ln58_fu_551_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(icmp_ln63_fu_611_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state9.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state9.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                    esl_seteq<1,1,1>(icmp_ln58_fu_551_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(icmp_ln63_fu_611_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && 
         esl_seteq<1,1,1>(icmp_ln54_fu_515_p2.read(), ap_const_lv1_1))) {
        crc_0_reg_191 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln58_fu_551_p2.read()))) {
        crc_0_reg_191 = crc_fu_603_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i1_0_reg_180 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())))) {
        i1_0_reg_180 = i_fu_521_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && 
         esl_seteq<1,1,1>(icmp_ln54_fu_515_p2.read(), ap_const_lv1_1))) {
        i2_0_reg_202 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln58_fu_551_p2.read()))) {
        i2_0_reg_202 = i_6_fu_557_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln58_fu_551_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(icmp_ln63_fu_611_p2.read(), ap_const_lv1_1))) {
        i3_0_reg_213 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln68_fu_617_p2.read()))) {
        i3_0_reg_213 = i_7_fu_623_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_0_reg_168 = i_5_reg_662.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_0_reg_168 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && esl_seteq<1,2,2>(trunc_ln55_fu_527_p1.read(), ap_const_lv2_1))) {
        crc_t_3_1_fu_106 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && esl_seteq<1,2,2>(trunc_ln55_fu_527_p1.read(), ap_const_lv2_2))) {
        crc_t_3_2_fu_110 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && esl_seteq<1,2,2>(trunc_ln55_fu_527_p1.read(), ap_const_lv2_3))) {
        crc_t_3_3_fu_114 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && esl_seteq<1,2,2>(trunc_ln55_fu_527_p1.read(), ap_const_lv2_0))) {
        crc_t_3_fu_102 = e_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        i_5_reg_662 = i_5_fu_230_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln41_reg_658 = icmp_ln41_fu_224_p2.read();
        icmp_ln41_reg_658_pp0_iter1_reg = icmp_ln41_reg_658.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln68_reg_711 = icmp_ln68_fu_617_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        lshr_ln49_3_reg_672 = select_ln49_2_fu_349_p3.read().range(31, 1);
        select_ln49_2_reg_667 = select_ln49_2_fu_349_p3.read();
    }
}

void CRCCheck_do_gen::thread_R_fu_253_p2() {
    R_fu_253_p2 = (ap_phi_mux_R_0_phi_fu_160_p4.read() ^ zext_ln46_fu_241_p1.read());
}

void CRCCheck_do_gen::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void CRCCheck_do_gen::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[6];
}

void CRCCheck_do_gen::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void CRCCheck_do_gen::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void CRCCheck_do_gen::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[4];
}

void CRCCheck_do_gen::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[5];
}

void CRCCheck_do_gen::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CRCCheck_do_gen::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CRCCheck_do_gen::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln68_reg_711.read()) && esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln68_reg_711.read()) && esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln68_reg_711.read()) && esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_state10_pp1_stage0_iter1() {
    ap_block_state10_pp1_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln68_reg_711.read()) && esl_seteq<1,1,1>(ap_const_logic_0, s_full_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CRCCheck_do_gen::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CRCCheck_do_gen::thread_ap_block_state7() {
    ap_block_state7 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()));
}

void CRCCheck_do_gen::thread_ap_block_state9_pp1_stage0_iter0() {
    ap_block_state9_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CRCCheck_do_gen::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln41_fu_224_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_ap_condition_pp1_exit_iter0_state9() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln68_fu_617_p2.read())) {
        ap_condition_pp1_exit_iter0_state9 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state9 = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void CRCCheck_do_gen::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void CRCCheck_do_gen::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_ap_phi_mux_R_0_phi_fu_160_p4() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_reg_658_pp0_iter1_reg.read()))) {
        ap_phi_mux_R_0_phi_fu_160_p4 = select_ln49_7_fu_507_p3.read();
    } else {
        ap_phi_mux_R_0_phi_fu_160_p4 = R_0_reg_156.read();
    }
}

void CRCCheck_do_gen::thread_ap_phi_mux_i_0_phi_fu_172_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0))) {
        ap_phi_mux_i_0_phi_fu_172_p4 = i_5_reg_662.read();
    } else {
        ap_phi_mux_i_0_phi_fu_172_p4 = i_0_reg_168.read();
    }
}

void CRCCheck_do_gen::thread_crc_fu_603_p3() {
    crc_fu_603_p3 = esl_concat<24,8>(trunc_ln59_1_fu_599_p1.read(), tmp_11_fu_585_p6.read());
}

void CRCCheck_do_gen::thread_e_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read())))) {
        e_blk_n = e_empty_n.read();
    } else {
        e_blk_n = ap_const_logic_1;
    }
}

void CRCCheck_do_gen::thread_e_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read()))))) {
        e_read = ap_const_logic_1;
    } else {
        e_read = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_i_5_fu_230_p2() {
    i_5_fu_230_p2 = (!ap_phi_mux_i_0_phi_fu_172_p4.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(ap_phi_mux_i_0_phi_fu_172_p4.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void CRCCheck_do_gen::thread_i_6_fu_557_p2() {
    i_6_fu_557_p2 = (!i2_0_reg_202.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i2_0_reg_202.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void CRCCheck_do_gen::thread_i_7_fu_623_p2() {
    i_7_fu_623_p2 = (!i3_0_reg_213.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i3_0_reg_213.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void CRCCheck_do_gen::thread_i_fu_521_p2() {
    i_fu_521_p2 = (!i1_0_reg_180.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i1_0_reg_180.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void CRCCheck_do_gen::thread_ibuffer_V_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        ibuffer_V_address0 =  (sc_lv<7>) (zext_ln70_fu_629_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ibuffer_V_address0 =  (sc_lv<7>) (zext_ln45_fu_236_p1.read());
    } else {
        ibuffer_V_address0 = "XXXXXXX";
    }
}

void CRCCheck_do_gen::thread_ibuffer_V_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)))) {
        ibuffer_V_ce0 = ap_const_logic_1;
    } else {
        ibuffer_V_ce0 = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_ibuffer_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_reg_658.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ibuffer_V_we0 = ap_const_logic_1;
    } else {
        ibuffer_V_we0 = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_icmp_ln41_fu_224_p2() {
    icmp_ln41_fu_224_p2 = (!ap_phi_mux_i_0_phi_fu_172_p4.read().is_01() || !ap_const_lv7_44.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_0_phi_fu_172_p4.read() == ap_const_lv7_44);
}

void CRCCheck_do_gen::thread_icmp_ln54_fu_515_p2() {
    icmp_ln54_fu_515_p2 = (!i1_0_reg_180.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_180.read() == ap_const_lv3_4);
}

void CRCCheck_do_gen::thread_icmp_ln58_fu_551_p2() {
    icmp_ln58_fu_551_p2 = (!i2_0_reg_202.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_202.read() == ap_const_lv3_4);
}

void CRCCheck_do_gen::thread_icmp_ln63_fu_611_p2() {
    icmp_ln63_fu_611_p2 = (!crc_0_reg_191.read().is_01() || !R_0_reg_156.read().is_01())? sc_lv<1>(): sc_lv<1>(crc_0_reg_191.read() == R_0_reg_156.read());
}

void CRCCheck_do_gen::thread_icmp_ln68_fu_617_p2() {
    icmp_ln68_fu_617_p2 = (!i3_0_reg_213.read().is_01() || !ap_const_lv7_44.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_213.read() == ap_const_lv7_44);
}

void CRCCheck_do_gen::thread_lshr_ln49_1_fu_297_p4() {
    lshr_ln49_1_fu_297_p4 = select_ln49_fu_285_p3.read().range(31, 1);
}

void CRCCheck_do_gen::thread_lshr_ln49_2_fu_329_p4() {
    lshr_ln49_2_fu_329_p4 = select_ln49_1_fu_317_p3.read().range(31, 1);
}

void CRCCheck_do_gen::thread_lshr_ln49_4_fu_391_p4() {
    lshr_ln49_4_fu_391_p4 = select_ln49_3_fu_379_p3.read().range(31, 1);
}

void CRCCheck_do_gen::thread_lshr_ln49_5_fu_423_p4() {
    lshr_ln49_5_fu_423_p4 = select_ln49_4_fu_411_p3.read().range(31, 1);
}

void CRCCheck_do_gen::thread_lshr_ln49_6_fu_455_p4() {
    lshr_ln49_6_fu_455_p4 = select_ln49_5_fu_443_p3.read().range(31, 1);
}

void CRCCheck_do_gen::thread_lshr_ln49_7_fu_487_p4() {
    lshr_ln49_7_fu_487_p4 = select_ln49_6_fu_475_p3.read().range(31, 1);
}

void CRCCheck_do_gen::thread_lshr_ln_fu_265_p4() {
    lshr_ln_fu_265_p4 = R_fu_253_p2.read().range(31, 1);
}

void CRCCheck_do_gen::thread_s_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln68_reg_711.read()))) {
        s_blk_n = s_full_n.read();
    } else {
        s_blk_n = ap_const_logic_1;
    }
}

void CRCCheck_do_gen::thread_s_din() {
    s_din = ibuffer_V_q0.read();
}

void CRCCheck_do_gen::thread_s_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln68_reg_711.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        s_write = ap_const_logic_1;
    } else {
        s_write = ap_const_logic_0;
    }
}

void CRCCheck_do_gen::thread_select_ln49_1_fu_317_p3() {
    select_ln49_1_fu_317_p3 = (!trunc_ln49_fu_293_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln49_fu_293_p1.read()[0].to_bool())? xor_ln49_1_fu_311_p2.read(): zext_ln49_1_fu_307_p1.read());
}

void CRCCheck_do_gen::thread_select_ln49_2_fu_349_p3() {
    select_ln49_2_fu_349_p3 = (!trunc_ln49_1_fu_325_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln49_1_fu_325_p1.read()[0].to_bool())? xor_ln49_2_fu_343_p2.read(): zext_ln49_2_fu_339_p1.read());
}

void CRCCheck_do_gen::thread_select_ln49_3_fu_379_p3() {
    select_ln49_3_fu_379_p3 = (!trunc_ln49_2_fu_367_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln49_2_fu_367_p1.read()[0].to_bool())? xor_ln49_3_fu_373_p2.read(): zext_ln49_3_fu_370_p1.read());
}

void CRCCheck_do_gen::thread_select_ln49_4_fu_411_p3() {
    select_ln49_4_fu_411_p3 = (!trunc_ln49_3_fu_387_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln49_3_fu_387_p1.read()[0].to_bool())? xor_ln49_4_fu_405_p2.read(): zext_ln49_4_fu_401_p1.read());
}

void CRCCheck_do_gen::thread_select_ln49_5_fu_443_p3() {
    select_ln49_5_fu_443_p3 = (!trunc_ln49_4_fu_419_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln49_4_fu_419_p1.read()[0].to_bool())? xor_ln49_5_fu_437_p2.read(): zext_ln49_5_fu_433_p1.read());
}

void CRCCheck_do_gen::thread_select_ln49_6_fu_475_p3() {
    select_ln49_6_fu_475_p3 = (!trunc_ln49_5_fu_451_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln49_5_fu_451_p1.read()[0].to_bool())? xor_ln49_6_fu_469_p2.read(): zext_ln49_6_fu_465_p1.read());
}

void CRCCheck_do_gen::thread_select_ln49_7_fu_507_p3() {
    select_ln49_7_fu_507_p3 = (!trunc_ln49_6_fu_483_p1.read()[0].is_01())? sc_lv<32>(): ((trunc_ln49_6_fu_483_p1.read()[0].to_bool())? xor_ln49_7_fu_501_p2.read(): zext_ln49_7_fu_497_p1.read());
}

void CRCCheck_do_gen::thread_select_ln49_fu_285_p3() {
    select_ln49_fu_285_p3 = (!xor_ln46_1_fu_259_p2.read()[0].is_01())? sc_lv<32>(): ((xor_ln46_1_fu_259_p2.read()[0].to_bool())? xor_ln49_fu_279_p2.read(): zext_ln49_fu_275_p1.read());
}

void CRCCheck_do_gen::thread_tmp_11_fu_585_p5() {
    tmp_11_fu_585_p5 = (trunc_ln59_fu_575_p1.read() ^ ap_const_lv2_3);
}

void CRCCheck_do_gen::thread_trunc_ln46_1_fu_249_p1() {
    trunc_ln46_1_fu_249_p1 = ap_phi_mux_R_0_phi_fu_160_p4.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln46_fu_245_p1() {
    trunc_ln46_fu_245_p1 = e_dout.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln49_1_fu_325_p1() {
    trunc_ln49_1_fu_325_p1 = select_ln49_1_fu_317_p3.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln49_2_fu_367_p1() {
    trunc_ln49_2_fu_367_p1 = select_ln49_2_reg_667.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln49_3_fu_387_p1() {
    trunc_ln49_3_fu_387_p1 = select_ln49_3_fu_379_p3.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln49_4_fu_419_p1() {
    trunc_ln49_4_fu_419_p1 = select_ln49_4_fu_411_p3.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln49_5_fu_451_p1() {
    trunc_ln49_5_fu_451_p1 = select_ln49_5_fu_443_p3.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln49_6_fu_483_p1() {
    trunc_ln49_6_fu_483_p1 = select_ln49_6_fu_475_p3.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln49_fu_293_p1() {
    trunc_ln49_fu_293_p1 = select_ln49_fu_285_p3.read().range(1-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln55_fu_527_p1() {
    trunc_ln55_fu_527_p1 = i1_0_reg_180.read().range(2-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln59_1_fu_599_p1() {
    trunc_ln59_1_fu_599_p1 = crc_0_reg_191.read().range(24-1, 0);
}

void CRCCheck_do_gen::thread_trunc_ln59_fu_575_p1() {
    trunc_ln59_fu_575_p1 = i2_0_reg_202.read().range(2-1, 0);
}

void CRCCheck_do_gen::thread_xor_ln46_1_fu_259_p2() {
    xor_ln46_1_fu_259_p2 = (trunc_ln46_1_fu_249_p1.read() ^ trunc_ln46_fu_245_p1.read());
}

void CRCCheck_do_gen::thread_xor_ln49_1_fu_311_p2() {
    xor_ln49_1_fu_311_p2 = (zext_ln49_1_fu_307_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_xor_ln49_2_fu_343_p2() {
    xor_ln49_2_fu_343_p2 = (zext_ln49_2_fu_339_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_xor_ln49_3_fu_373_p2() {
    xor_ln49_3_fu_373_p2 = (zext_ln49_3_fu_370_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_xor_ln49_4_fu_405_p2() {
    xor_ln49_4_fu_405_p2 = (zext_ln49_4_fu_401_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_xor_ln49_5_fu_437_p2() {
    xor_ln49_5_fu_437_p2 = (zext_ln49_5_fu_433_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_xor_ln49_6_fu_469_p2() {
    xor_ln49_6_fu_469_p2 = (zext_ln49_6_fu_465_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_xor_ln49_7_fu_501_p2() {
    xor_ln49_7_fu_501_p2 = (zext_ln49_7_fu_497_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_xor_ln49_fu_279_p2() {
    xor_ln49_fu_279_p2 = (zext_ln49_fu_275_p1.read() ^ ap_const_lv32_82F63B78);
}

void CRCCheck_do_gen::thread_zext_ln45_fu_236_p1() {
    zext_ln45_fu_236_p1 = esl_zext<64,7>(i_0_reg_168.read());
}

void CRCCheck_do_gen::thread_zext_ln46_fu_241_p1() {
    zext_ln46_fu_241_p1 = esl_zext<32,8>(e_dout.read());
}

void CRCCheck_do_gen::thread_zext_ln49_1_fu_307_p1() {
    zext_ln49_1_fu_307_p1 = esl_zext<32,31>(lshr_ln49_1_fu_297_p4.read());
}

void CRCCheck_do_gen::thread_zext_ln49_2_fu_339_p1() {
    zext_ln49_2_fu_339_p1 = esl_zext<32,31>(lshr_ln49_2_fu_329_p4.read());
}

void CRCCheck_do_gen::thread_zext_ln49_3_fu_370_p1() {
    zext_ln49_3_fu_370_p1 = esl_zext<32,31>(lshr_ln49_3_reg_672.read());
}

void CRCCheck_do_gen::thread_zext_ln49_4_fu_401_p1() {
    zext_ln49_4_fu_401_p1 = esl_zext<32,31>(lshr_ln49_4_fu_391_p4.read());
}

void CRCCheck_do_gen::thread_zext_ln49_5_fu_433_p1() {
    zext_ln49_5_fu_433_p1 = esl_zext<32,31>(lshr_ln49_5_fu_423_p4.read());
}

void CRCCheck_do_gen::thread_zext_ln49_6_fu_465_p1() {
    zext_ln49_6_fu_465_p1 = esl_zext<32,31>(lshr_ln49_6_fu_455_p4.read());
}

void CRCCheck_do_gen::thread_zext_ln49_7_fu_497_p1() {
    zext_ln49_7_fu_497_p1 = esl_zext<32,31>(lshr_ln49_7_fu_487_p4.read());
}

void CRCCheck_do_gen::thread_zext_ln49_fu_275_p1() {
    zext_ln49_fu_275_p1 = esl_zext<32,31>(lshr_ln_fu_265_p4.read());
}

void CRCCheck_do_gen::thread_zext_ln70_fu_629_p1() {
    zext_ln70_fu_629_p1 = esl_zext<64,7>(i3_0_reg_213.read());
}

void CRCCheck_do_gen::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln41_fu_224_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln41_fu_224_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())) && esl_seteq<1,1,1>(icmp_ln54_fu_515_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln54_fu_515_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_0, e_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln58_fu_551_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(icmp_ln63_fu_611_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln58_fu_551_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_611_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 64 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln68_fu_617_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln68_fu_617_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

}

